### ISSUE TITLE
Publishing an empty post shows an incorrect "Post published" notice

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#1032]
## Expected behavior
When trying to publish an empty post - not title, no content, no excerpt - it should show an error message, "You can't publish an empty post."

## Current behavior
When you publish an empty post, it shows a "Post published" notice with a link to the new post. However, the post was not actually published and the link leads to a 404 error.

## Possible solution
When an empty post is published, it should result in an error notice "You can't publish an empty post."

## Steps to reproduce (for bugs)
1. Create an empty post, no title, no content, no excerpt.
2. Publish it. You will see "Post published" notice".

## Context
There is a function that performs this check and prevents post from being published:
https://developer.wordpress.org/reference/hooks/wp_insert_post_empty_content/

![image](https://user-images.githubusercontent.com/1692600/177050099-1580cbee-8794-4155-8ee2-99782170c126.png)

**Comment by smileBeda** [comment]
What should happen is that the post name (slug) gets populated with the ID of the new post. The ID is something generated by SQL on submit since it’s auto increment column.

this is how’s looking when publishing an empty post on WP since ever:
![C3CDE7DC-92B7-44CC-90F7-E38DBD58AF84](https://user-images.githubusercontent.com/11800236/177063435-4656a36d-c01d-4713-82bb-7b341489a97e.jpeg)

post body and excerpt and post title are not required items and neither should be required items.

I confirm however this is broken in CP

**Comment by viktorix** [comment]
I agree, we should be able to save an empty post especially if there was content before and we're trying to save an empty post to delete content. That was my original issue, which we were discussing on Slack. Then realized there's a function that checks for empty posts. 

There is a ticket in trac about saving an empty post related to Gutenberg. They're not fixing it.

**Comment by xxsimoxx** [comment]
In ClassicPress v2 the post is published.

**Comment by KTS915** [comment]
Actually, it isn't post but saved as an auto-draft. But the message says it's published — and that's the problem.
