### ISSUE TITLE
Expected type 'string'. Found 'null'

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#1055]
## Expected behavior
No error in IDE.

## Current behavior
Expected type 'string'. Found 'null'
https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-includes/update.php#L130
`. '?' . http_build_query( $query, null, '&' );`

## Possible solution
Change null to an empty string.
`. '?' . http_build_query( $query, '', '&' );`

## Context
Not sure if this is an issue or not. While working on a backport I noticed an error in update.php file. After reviewing [PHP docs for http_build_query](https://www.php.net/manual/en/function.http-build-query.php), the second parameter must be a string not null. Maybe there's a reason null is used, but I thought I'll log an issue just to keep an eye on it.

```
http_build_query(
    array|object $data,
    string $numeric_prefix = "",
    ?string $arg_separator = null,
    int $encoding_type = PHP_QUERY_RFC1738
): string

```

**Comment by smileBeda** [comment]
This error is thrown in wp at least since 
`[Jan 12 03:03:09:1641956589.487360:4:error] http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated (8192) File: /wp-includes/Requests/Transport/cURL.php Line: 345`

even thou php doc does not mention any change in php8, wp core assumes this to be a php8 compatibility fix:
https://core.trac.wordpress.org/ticket/53635#comment:146

Are you using php8, and is this as well happening with php < 8?

**Comment by bahiirwa** [comment]
It's a PHP 8 compat issue. It Can be seen when we fix our process.

**Comment by smileBeda** [comment]
Actually, if I get this right, it’s not even a php8 issue
It’s a deprecation notice for php 9

**Comment by bahiirwa** [comment]
Exactly. PHP 8 throws warnings and those become errors in 9.0
Ref: https://core.trac.wordpress.org/ticket/53635#comment:153

**Comment by bahiirwa** [comment]
I will refer this issue in #687 and close this for now.
It can be reopened if need be.

**Comment by viktorix** [comment]
Yes, my VS Code uses PHP8. Thanks.
