### ISSUE TITLE
Future Fixes Strict Type Checks 

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#1098]
Note that this](https://github.com/ClassicPress/ClassicPress/pull/1067) is just one of the many issues fixed on [WordPress/WordPress@7932193](https://github.com/WordPress/WordPress/commit/793219370873406823395e33051b6c7e8c27b2e2)
Fixed in https://core.trac.wordpress.org/changeset/47808

There are a number of fixes in this [ticket 49542](https://core.trac.wordpress.org/ticket/49542)

_Originally posted by @bahiirwa in https://github.com/ClassicPress/ClassicPress/issues/1067#issuecomment-1193131457_

**Comment by mattyrob** [comment]
There is a huge amount of backporting work to be done for PHP 8 and 8.1

I may not even have all of it but this is the list I have so far, and it would be massively helpful to apply these in order to avoid merge conflicts as much as possible.

https://core.trac.wordpress.org/ticket/45934 - 12
https://core.trac.wordpress.org/ticket/47632 - 27
https://core.trac.wordpress.org/ticket/49222 - 8
https://core.trac.wordpress.org/ticket/49542 - 37
https://core.trac.wordpress.org/ticket/50343 - 2
https://core.trac.wordpress.org/ticket/50913 - 33
https://core.trac.wordpress.org/ticket/52825 - 1
https://core.trac.wordpress.org/ticket/53299 - 1
https://core.trac.wordpress.org/ticket/53465 - ?
https://core.trac.wordpress.org/ticket/53635 - 41

**Comment by bahiirwa** [comment]
Tracking these here
- [x] 45934 https://core.trac.wordpress.org/ticket/45934 
  - [ ] Has PR - https://github.com/ClassicPress/ClassicPress/pull/1101
  - [ ] Merged

- [ ] 47632 https://core.trac.wordpress.org/ticket/47632
  - [ ] Has PR
  - [ ] Merged
  
- [ ] 49222 https://core.trac.wordpress.org/ticket/49222
  - [ ] Has PR
  - [ ] Merged
  
- [ ] 49542 https://core.trac.wordpress.org/ticket/49542
  - [ ] Has PR
  - [ ] Merged
  
- [ ] 50343 https://core.trac.wordpress.org/ticket/50343
  - [ ] Has PR
  - [ ] Merged
  
- [ ] 50913 https://core.trac.wordpress.org/ticket/50913
  - [ ] Has PR
  - [ ] Merged
  
- [ ] 52825 https://core.trac.wordpress.org/ticket/52825
  - [ ] Has PR
  - [ ] Merged
  
- [ ] 53299 https://core.trac.wordpress.org/ticket/53299
  - [ ] Has PR
  - [ ] Merged
  
- [ ] 53465 https://core.trac.wordpress.org/ticket/53465 
  - [ ] Has PR
  - [ ] Merged
  
- [ ] 53635 https://core.trac.wordpress.org/ticket/53635
  - [ ] Has PR
  - [ ] Merged

**Comment by mattyrob** [comment]
I started looking at Ticket 49222 today but there are file location changes from 47632 that probably need to be merged first.

Additionally, it seems like packporting changes from [45059](https://core.trac.wordpress.org/ticket/45059) might be sensible.

**Comment by viktorix** [comment]
Do we still want to put in the work on this PR to include it in 1.6.0?
