### ISSUE TITLE
💡 ClassicPress version issues and conflict with plugins

### ISSUE THREAD

**Issue by samjco** [ClassicPress/ClassicPress#1148]
### Context

The version of ClassicPress doesn't match the latest version of WordPress nor doesn't sometimes match what mainstream plugins need for it to work.

### Possible implemantion

Make a way for users to manually change the version so that they can use and test mainstream plugins that require a certain version in order to use them.

### Possible Solution

I have been manually changing the plugin's version to allow to use with the current version of ClassicPress. And to my surprise, a lot of them actually work! So my suggestion is to.., in addition to making a way to change the version of ClassicPress internally, at the same time, allow ClassicPress users to test of many plugins and to have a button that will report back to a CP repo that this plugin works. 

### Will you be able to help with the implementation?

I can actually build a options page to change global data, db data, etc, as well as a way to REST post data to a remote location to show which plugins work.. I would just need to know what ALL places to affect, change, when it comes to the version of ClassicPress. Like, where are all the area/locations that the version number is being stored.

**Comment by smileBeda** [comment]
This is not an optimal solution to the problem at hand.

1. plugins might work, but that’s just the appearance. Below the surface, it might actually not work
2. It’s better to either have those plugins update their minimal required versions or have them officially support cp
3. Even better is to maintain plugins _made for_ cp that cover those areas

Everyone is free to hack the code versions but this shouldn’t ever be a core option.

**Comment by samjco** [comment]
interesting...

I agree, maybe not for core. Maybe plugin territory. Or maybe a core plugin?
My thoughts are that this is what is needed to push the needle forward in getting more plugins available. My reasons.
1. Plugin developers may never decide to develop/undevelop, update their plugins for CP vs WP
2. Right now, the many users of CP are not able to fully test plugins...

Maybe another versions of CP should be made available so developers can test the latest plugins..
For instance JSM Meta plugin shows non capable with CP, but it works 100% with CP.

**Comment by smileBeda** [comment]
Core plugin would be intended to be delivered with core, so I wouldn't opt for that - it will encourage users to do things they shouldn't be doing.

As a plugin, of course anyone is free to develop such and list it as a developer plugin on the CP Plugin Directory.
If, then that IMO is the only way to (unless manually editing) provide such feature without cutting into our own flesh.

The problem is, as said, testing a plugin and concluding it is _working_ is not really enough. Sometimes, it takes hundreds of hours or even days to find things that do not "work", or scan code for possible functions, logic or else that in CP wouldn't work.
Finally, changing the version number of CP would probably mess with the update process (as it would assume the current installed CP version is _higher_ than what the update server wants to deliver to the user's install). Thus, it'd not update, and leave installs outdated, at best, vulnerable at worst.

Therefore, I would even consider a plugin doing such manipulation of version numbers "dangerous" and definitely only allow it as a "You must know what you are messing with" on the directory :)

**Comment by samjco** [comment]
_"The problem is, as said, testing a plugin and concluding it is working is not really enough. Sometimes, it takes hundreds of hours or even days to find things that do not "work", or scan code for possible functions, logic or else that in CP wouldn't work."_
But isn't that WordPress in a nut shell and the essense of opensource?

_"- it will encourage users to do things they shouldn't be doing."_
Respectfully , disagree. if($opensource === "Doing what we want.") return true;

My thoughts is what do the community think? If no forward movement, simple folk CP and make CPx. Match WP versions to have the new CPx community test out plugins to their hearts content and allow users who are speaking my same language - Press on!

**Comment by samjco** [comment]
Ok.

My main use of CP was to make a web app without the bloat. 
And I have committed and contributed a ton to the WP Community so I can understand some of the different needs. In my opinion ClassicPress should be called WordPressless or WordPressX. Or simply the tag-line "WordPress without the bloat". But to go into a whole another direction , a new identity, aside WordPress is a monumental undertaking... and that is why I am now understanding the backlash to my feature request. 

However, because of my needs to why I've downloaded CP in the first place, I feel that expressing concern to fixed an issue that my type of person is experiencing is valid and shouldn't be shot down so quickly. Keep in mind commiters are not owners to a particular open source code the are really "tennis or volley ball players" to the code. So they can't really make a direction to a particular product, they can only "serve it up" in a different way.. until someone come along and gets denied to a feature to something and then they fork and "serve it" the way they feel thanks to GPL. 

As to tennis and volleyball, someone is bound to ace or spike - but I think that depends on how much of a community you have to support you.

So now my request has changed to... if I build a plugin for ClassicPress (the unversion version, the "use at our own risk version") that will change the version to keep pace with WordPress' version, would the ClassicPress admins allow it on the repository?

**Comment by mattyrob** [comment]
The current ClassicPress code stops end users from downloading and installing plugins from the main WordPress plugin repository if the plugin files declare that they don't support ClassicPress (i.e. they state they require a version of WordPress above 4.9)

That said, some plugins don't declare this information and are still incompatible, and some declause they won't work when in fact they do.

One solution to your suggestion already exists, you can download and install the plugin files using FTP, activation of the plugin will not be blocked at this stage (only installation) but as I'm sure you can understand, as ClassicPress is not in step with WordPress it may give you PHP errors - either on activation or later down the line if required functions are not available.

**Comment by KTS915** [comment]
One issue that I can see with this proposal, and which has not been mentioned so far, is that this could mess up the process for updating core, since it will prevent the identification of the correct version. Indeed, this could lead to the site being updated to the latest version of WP instead.

If you really want to go down this route and don't want to go down the FTP route (which, like @mattyrob, is what I do), wouldn't it be better to create a plugin that changes the "Required" header in select plugins?

**Comment by smileBeda** [comment]
I did indeed mention the update issue in my reply here https://github.com/ClassicPress/ClassicPress/issues/1148#issuecomment-1301843372 😉

@samjco you might be interested in WordPress CMS: https://github.com/wp-cms/wp-cms
It’s pretty much what you describe in your last reply.

**Comment by viktorix** [comment]
> the unversion version, the "use at our own risk version" (@samjco )
> this could mess up the process for updating core (@KTS915)

What if we introduced a filter that would allow user to set their own core version which would exclude core updates? For example: `add_filter( 'classicpress_version', '6.0.3' );`

Plugins and themes think it's 6.0.3, but the core update process would continue to know the real CP version. I would also exclude generator tag modification.

This makes CP customizable with minimal effort, and anyone using the filter accepts that risk.

**Comment by KTS915** [comment]
The problem with that suggestion is that it then potentially messes with every other plugin and theme, which could cause all sorts of unexpected behaviors (and, no doubt, many complaints). If something like this were to be done, it would be much better to focus on how to make a change for each plugin separately.

**Comment by smileBeda** [comment]
Truly - if someone takes the risk to take down his (maybe testing) site, or risk a bad update from core using any sort of core feature… then opening the code editor, and editing that version number shouldn’t be a showstopper (or just download said plugin to test manually).

If that’s too much work to test a plugin for compatibility (which even if resulting positive doesn’t mean at all said plugin should be broadly used on a cp install) then probably the person doing the tests shouldn’t be doing these tests because they also wouldn’t look at a debug log or digging into API compatibility etc.

The amount of work needed to make this change in core as feature, compared to the benefit it actually brings is not justifiable imo. Plugins not supporting a certain version _have reasons to do so_. Maybe they are _planning to add code that isn’t supported_ and do it the right way by first dropping support, or, plain simple don’t 100% work.

Thumbs down for this feature proposal for the reason mentioned prior.

**Comment by xxsimoxx** [comment]
> What if we introduced a filter 

I've tried this solution, filtering `$wp_version` in `includes/version.php`.
- It let you install unsupported plugins, but even if a plugin do not activate because of the "sandboxed" activation, uninstalling resulted in a WSOD that needed shell (or FTP) access to solves.
- It breaks `wp-cli`.

**Comment by samjco** [comment]
Here's the thing. We are all developers here. We can make anything we want. 
We can make a filter, yes, to do as @viktorix mentioned. And at the same time make a way to undo plugins from the address bar the same way Code Snippets, Woody Snippets, currently works. 

Is ClassicPress closed source or not?

**Comment by samjco** [comment]
I guess by text the word "closed" somehow closes the thread.... must be a bug in github mobile.

**Comment by smileBeda** [comment]
ClassicPress is not closed source. But open source does not mean that we should consider using plugins that _do not support the CMS_ - solely based on a few user reviews.

The only _real_ solid hint to use a plugin on CP is either it is _supporting CP_ or it is _built for CP_

What is the _benefit_ of having an approach where users can test what works or not "easier" than they can already do that now?
Only more "it works" statements around and (already happened several times) issues such as "I tested the plugin, it worked, I used it, ups I got hacked because the plugin wasn't updated anymore due to unsupported version..." will then transform to to "I tested the plugin, it worked, you just need to fake CP version, ups I got hacked because the CMS wasn't updated anymore due to version mismatch"

This is a _security_ issue. 
When you use an outdated Mac OS or fake its version in any way just to run your favourite App that does not support the newest version (or vice versa), it is _your_ choice to do so, and you are absolutely free to do so, but it does not bring any advantage to anyone else who is not aware of the risks.

Let's make a scenario:
1. You find a plugin that works on CP because you fake CP version.
2. You run the plugin, but want to keep the CP updates coming, so you "unfake" the CP version. 
3. You will now not get any plugin updates anymore, it will keep working, until you get hacked because you'd not receive the plugin security updates anymore either.
4. Or, you keep the fake CP version, you don't get CP updates anymore, and again you will get hacked sooner or later due to outdated CMS

Yes, with code we can solve anything, perhaps we could save the "real" version somewhere, so CP knows this is a "fake" version and still pushes updates, but again, what is the _benefit_ of this compared to the work, also keeping in mind that this CMS is not yet even compatible with PHP 8, which will be in about 10 days the _only_ actively supported PHP version out there?
If we would have hundreds of volunteers working at core, such feature could _maybe_ be considered, but then, with hundreds of volunteers we also would have many more plugins, and such feature would become obsolete again.

All in all, implementing this is not going to help the system. It is going to hurt it, because on the long run, everyone will _keep using plugins intended for WP_. And nothing will ever be done about that - which is the real core problem here: there are not enough plugins working on CP. Faking CP version is not going to _solve_ that, it is putting a bandaid on it.

I think there have been outlined enough reasons here as of why _not_ - can you outline reasons as of why _yes_, apart of the ability to save 10 seconds work involved in manual downloads and tests of _unsupported_ plugins? Reasons that outweigh the cons? Reasons other than "the project os OSS and thus we should implement whatever we dream of today"?


I do not want to come over patronising, I _do understand_ the issue, and have the utmost respect for every idea, but this is not something we should put into core, for the outlined valid reasons. It is dangerous, that's really all, and does not help testing or create an incentive to test and does not resolve the core problem.

**Comment by KTS915** [comment]
There is now a plugin (not a core plugin) for this. See https://directory.classicpress.net/plugins/wp-version-modifier-for-cp/

So I'm closing this as moot.
