### ISSUE TITLE
What to do with plugin installation section

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress#117]
As per [this discussion on Slack](https://classicpress.slack.com/archives/CCH2X1VNG/p1538950152000100) and @nylen suggestion to [make it an issue](https://classicpress.slack.com/archives/CCH2X1VNG/p1538965799000100), I'm opening it as an issue so it doesn't get lost.

## Possibilities
There are several possibilities brought up in the discussion
* remove all, keep search
* leave as is, but remove Gutenberg and related, and do the improvements in v2
* remove featured tab and switch first tab to search box
* **NEW IDEA** change current popular tab with latest plugins that have been added to the Plugins Directory and of course the Search tab may stay, rest removed

More possible

**Comment by nylen** [comment]
I think it makes sense to remove **Beta Testing** and **Featured**, and keep **Popular**, **Recommended**, and **Favorites** (and of course the search box).

If we keep **Featured**, we need to change the text (there is no ClassicPress plugin directory).

---

Some screenshots of the existing sections, so we are clear on what we are talking about:

![2018-10-08t13 55 08-05 00](https://user-images.githubusercontent.com/227022/46628068-0d669580-cb02-11e8-817d-c0ed6dfa453a.png)
![2018-10-08t13 55 17-05 00](https://user-images.githubusercontent.com/227022/46628067-0d669580-cb02-11e8-831e-1cf7dd13a174.png)
![2018-10-08t13 55 27-05 00](https://user-images.githubusercontent.com/227022/46628066-0d669580-cb02-11e8-8cd5-4a35b3b45402.png)
![2018-10-08t13 55 38-05 00](https://user-images.githubusercontent.com/227022/46628064-0d669580-cb02-11e8-8349-9b4dfd426c28.png)
![2018-10-08t13 55 50-05 00](https://user-images.githubusercontent.com/227022/46628062-0ccdff00-cb02-11e8-96ec-127eba76b000.png)

**Comment by senlin** [comment]
To be honest my vote would go to get rid of everything except the search box. Popular is most downloads (or most active installs) and are always the same. 

I think popular only makes sense when the user does a search on for example Contact forms and then Contact Form 7 pops out.

Maybe the user is looking for a forums plugin, the current popular plugins don't offer anything in that aspect. So popular is a term that doesn't mean anything and only emphasises the plugins that don't really need any additional advertising.

**Comment by senlin** [comment]
@Tmeister - thanks, done

**Comment by ruiguerreiro79** [comment]
like @Tmeister  said above I have the same concerns about an "empty" page.
My suggestion would be to create some categories links to provide some guidance to the user.

Something like the image attached that is based on Codecanyon categories.
<img width="887" alt="plugin-categories" src="https://user-images.githubusercontent.com/29898220/46698659-97e8eb00-cc0f-11e8-9400-169f5508dbf3.png">

In terms of behaviour to be simple to implement, i.e when you press the Forms category it would fill the search box with the "forms" term or link directly to the tag.

**Comment by nylen** [comment]
> change current popular tab with latest plugins that have been added to the Plugins Directory

I like the idea of finding a way to promote newer plugins, or letting plugin authors promote their plugins, but I have some concerns with doing this by just showing a list of the newest plugins, especially here and now.

- **Existing process for new features.**  It's debatable where to draw the line, but in my opinion adding a new section with new functionality is a "major change" that would go through a petition or at least a committee vote, and we've been trying not to introduce anything new into v1 without very good reason.  This is very different from removing content that is promoted by WP and really only applies to WP.
- **Development time.**  This is not a trivial thing to implement, for me it could be 5 to 10 hours to do it well.  Right now it's not clear where that dev time would come from.
- **Quality of what would appear on this screen.**  There are over 60,000 plugins in the repository, and growing every day.  Most new plugins are early alpha versions, intended for very specific use cases, not fully working, or some combination of the above.  I feel strongly that it's better to curate the list, whether by community usage, reviews, plugin authors recommending their own plugins and competing for spots, or some combination of the above.

So I think this is worth more thought, discussion, and planning, and worth doing right for v2 rather than rushing something into v1.  Other ideas could include a section where plugin authors can pay to promote their plugins, once they decide they're ready (I think the part where plugin authors decide when they're ready is important too).

There is a petition for this:  https://petitions.classicpress.net/posts/78/show-latest-plugins-on-plugin-install-screen

> I would like to see at least the Popular list, as a regular user I don't want to see empty pages, also think that the users have a WordPress background if they see an empty page they will think that there is a bug there.

I think I agree with this.  "Popular" plugins are plugins that have stood the test of time and are commonly used by all types of WP installs.

We could have two tabs: "Popular" (works much as it does today) and "What's Next" or "ClassicPress Plugins" (explaining how ClassicPress works with plugins today, and a call-to-action for new ClassicPress contributors, like plugin developers etc, to help us determine and implement a direction for this kind of issue).  Then of course the search box.

**Comment by nylen** [comment]
> My suggestion would be to create some categories links to provide some guidance to the user.

@ruiguerreiro79 This seems easier, and more feasible for v1.

I think with this approach we could remove the tabs entirely, and we'll want to add a message explaining that "all your favorite plugins are still here" etc.

**Comment by ruiguerreiro79** [comment]
@nylen in earlier committee meeting I mixed my 2 ideas along the discussion that didn't help for sure. Obviously, the "categories" idea was for V1 and the "Recent plugins" for V2 because it requires additional data and it needs more hours to be done.

Also it's important that text like you suggested ensuring that all plugins are available and should work without any issues.

I also think we can get rid of the tabs, also regarding that dropdown (tag, keyword, author) before the search field I never realized it was there till today. That search field in the right side it isn't in the best position.

**Comment by ginsterbusch** [comment]
For the category idea: We could also just use the pre-existing tags / categories from wp.org.
This one is being returned by calling https://api.wordpress.org/themes/info/1.1/?action=feature_list 

Documentation: https://codex.wordpress.org/WordPress.org_API#Feature_list (which is rather rudimentary / crude)

cu, w0lf.

**Comment by nylen** [comment]
@senlin @ruiguerreiro79 @ginsterbusch I was thinking we might keep the Popular tab, because I think these are the plugins that people are most likely to want to install.

Any specific objections to that?

I think we should also get a category-based solution working, ideally using the pre-existing tags / categories from wp.org, but someone needs to look through what appears for each tag and make sure this makes sense.

We should also include a message like "All your favorite plugins are still here ... use the search box to find them", especially if we remove the Popular tab.

Milestoning this issue for beta1, but let's come to an agreement soon about what to do here, and then split out this issue into separate tasks.

**Comment by nylen** [comment]
I actually think number of downloads or active installs is the best way to order this tab, and the best piece of information we can show in our plugins screen, since these are the plugins that people are most likely to want.

I also don't think it's a problem that some of these plugins are owned by Automattic.  WooCommerce, for example:  we want people to build large e-commerce sites on ClassicPress, it's an excellent test for us and for our primary use case (a business CMS).

The way I see it, we are not in competition with WordPress or Automattic, rather we are providing an alternative for a group of users that likely won't be well-served by their current direction.

**Comment by ruiguerreiro79** [comment]
So we would remove all the tabs just leaving the Popular plugins. I'm ok with that.

Regarding the Popular items I think that at the moment we don't have any other stats to measure a plugin popularity(like the growth in downloads or reviews score in the last 6 months) without being the number of downloads and the reviews.

Yes we need to map properly the categories with the tag terms, I guess for now we can stick with the most popular categories, anything else will need to be done in the search box.

In terms of UX this page was always a bit confuse to me.

I would suggest moving the search input to the left side since we are removing the tabs so it has the main focus. Below that we could have the Categories list and the Popular plugins.

**Comment by nylen** [comment]
Ok, I say let's go with that as a first step (search box at top left, and some way to display popular plugins and categories on the same page).

If we don't like it, we can make further changes from there, for example removing the popular plugins list.

**Comment by senlin** [comment]
sure

**Comment by nylen** [comment]
Now that I'm thinking about this some more, we'll want to be a little careful here, because this could be a breaking change for some people.

If we delete all the plugin tabs, but a plugin wants to add a new tab to this screen, what happens?

WPML is one example of a plugin that does some pretty heavy customization to parts of the plugin screens.  There are undoubtedly others, can anyone list other cases?

For more general discussion about breaking changes, see: https://github.com/ClassicPress/ClassicPress/issues/185

**Comment by ginsterbusch** [comment]
@senlin: I am using CF 7 quite a lot. I personally cannot understand people who would use something like Gravity Forms over having FULL control over how forms are being displayed, processed and the likes.

Also, there are quite a lot extremely well-done add-ons for CF 7, which the so-called "professional solutions" cannot compete with (yes, I've tested them, quite a lot).

cu, w0lf.

**Comment by senlin** [comment]
@ginsterbusch 
Fabian, every rule has its exceptions...

**Comment by ruiguerreiro79** [comment]
@nylen I wasn't aware of those hooks, and honestly this part of the "Add New plugin" never realized any change made by any plugin. Difficult to tell how many interact with those, but I can't see any way that this can break at the site level. It can break what those plugin authors have done with the tabs but that's it.   IMO I guess that is a specific area (only the Add new section) where I don't see too many issues if we limit the hooks.

There also other plugins when there isn't any hook available to do something they can rely on an HTML structure to append some code, those are even harder to discover so any change will always be a potential breaking change.

I also feel like you said that is bigger discussion like  #185

**Comment by nylen** [comment]
"Any change is a potential breaking change, so we shouldn't worry about it too much."

This is a common argument. It's not a very good one though: it's the responsibility of the people making the change (us) to not break sites.

I'd still like to see examples of plugins that modify the plugin screens.

**Comment by ruiguerreiro79** [comment]
not sure if the text in commas is related to what I said or not, because I didn't said that.  I was alerting to the fact that isn't just the changes that potentially remove hooks/filters that can cause an impact.

I also never saw any changes in that plugin section, I'm also curious to see what people have done there.

**Comment by mikeschinkel** [comment]
In Support of @ruiguerreiro79's idea regarding Codecanyon-like categories, there is some research I read a while back _(but can't find a link to right now)_ that said between 1/3rd and 2/3rds of people are "search" focused and the rest are "browse" focused.  So only having a search bar will not be so good for those people who are more browse focused.

I'd also argue the existing tabs are not good for many of the reasons already stated, but a list of categories would enable discovery and then browsing by use-case, the default list of featured categories could be easily updated over time, there could be a "more categories" link to show everything, and then within a category we could allow sorting for things like "popular", "featured", "highest rated", etc.

#jmtcw

**Comment by nylen** [comment]
If anyone can help implement something here, that would be good, otherwise this probably isn't going to make it into beta1.  Leaving it in the milestone for now.

**Comment by nylen** [comment]
This is not going to be ready in time for beta1.  Moving to 1.0.0-beta2 milestone.

**Comment by viktorix** [comment]
> like @Tmeister said above I have the same concerns about an "empty" page.
> My suggestion would be to create some categories links to provide some guidance to the user.
> 
> Something like the image attached that is based on Codecanyon categories.
> <img alt="plugin-categories" width="887" src="https://user-images.githubusercontent.com/29898220/46698659-97e8eb00-cc0f-11e8-9400-169f5508dbf3.png">
> 
> In terms of behaviour to be simple to implement, i.e when you press the Forms category it would fill the search box with the "forms" term or link directly to the tag.

I scanned through the discussion, is @ruiguerreiro79 suggestion currently the top one waiting to be implemented? It's a good idea.

**Comment by nylen** [comment]
Someone needs to spend a few hours trying this and looking at what is possible.  Otherwise for v1 we are just going to have to remove the obviously WP-specific sections and call it a day.

**Comment by ruiguerreiro79** [comment]
I did an experiment. At the moment I removed the other tabs just left the Popular plugins content.
The Categories list is just filling the input text and submitting the search form. I didn't change yet from Keyword to Tag search, but I think it's more accurate to use the tag option.

![img](https://cl.ly/03bee4f67237/Screen%20Recording%202019-01-17%20at%2002.28%20PM.gif)

let me know if this is the direction to go.

**Comment by viktorix** [comment]
Great job. It looks and functions pretty good. I agree that tags would be more accurate. And if possible, sort results by downloads count so more popular plugins would be at the top.

**Comment by ruiguerreiro79** [comment]
Great. 
I double check the results of the plugins API call. 

At the moment it's ordered by active installs, I think it's more expressive than the downloads because many downloads are done automatically and those plugins are never instaled. 

I think we can provide a more accurate Active Installs number. The top ones display 1+  Million, but we can show the detailed number 5 Million, 4 Million, 3 Million, etc

Also what's the point of showing more than 1900 potential pages of popular plugins. Maybe we can limit that to 1000 most popular plugins. It's just an idea, this has no effect in the performance since it's retrieving 30 results at each time.

**Comment by viktorix** [comment]
Active installs is really what I was referring to.

I would also recommend filtering out old plugins, maybe 4+ years with no updates. That would cut down results too.

**Comment by senlin** [comment]
> I would also recommend filtering out old plugins, maybe 4+ years with no updates

Actually if a plugin author cannot bother to update its plugin within two years the plugin should in my opinion be thrown out of the Directory.

**Comment by nylen** [comment]
@ruiguerreiro79 thanks!  I agree this looks like a good start, and probably a good place to end up for v1.  A few things I noticed from the screenshot:

- The text still says "Popular Plugins" after searching for a term.  This could say "Most Popular Plugins" at first, and then after you do a search it should say "Search Results" instead.
- The list of categories still appears after doing a search, which looks a bit weird.
- In the screenshot I don't see the submit button to do a search.  This should probably be right next to the search box.

> I think we can provide a more accurate Active Installs number. The top ones display 1+ Million, but we can show the detailed number 5 Million, 4 Million, 3 Million, etc

> Also what's the point of showing more than 1900 potential pages of popular plugins. Maybe we can limit that to 1000 most popular plugins. It's just an idea, this has no effect in the performance since it's retrieving 30 results at each time.

> I would also recommend filtering out old plugins, maybe 4+ years with no updates. That would cut down results too.

Unless these suggestions are really, really easy, then we need to save them for later.  We need to focus right now on the minimal changes possible to get v1 out the door, because we are already going to be at least a month behind our original schedule.

> Actually if a plugin author cannot bother to update its plugin within two years the plugin should in my opinion be thrown out of the Directory.

We can't control what the WP directory does of course, but I think when we have our own plugin directory then a rule like this will make a lot of sense.  @senlin can you post this over on https://forums.classicpress.net/c/plugins/plugin-directory please?

**Comment by ginsterbusch** [comment]
One nice idea for this would be to enhance it. Aside of the "Popular plugins" section. Because nothing says "we are doing stuff right" than doing things that are severly missing. Just today, when I was searching for some good Repost to Twitter plugins, I dearly missed an option to sort by rating.

cu, w0lf.

ps: well, with Gutenborg having that devastating ratings, wp.org certainly doesnt want THAT sorting option appear, do they? ;)

**Comment by ginsterbusch** [comment]
Ok, forget about it. As long as its wp.org, its .. like .. oh my. The usual shite with "whats important for wp.org" m(

9 bloody years, and still nobody thought its "important enough" to implement: 
- https://core.trac.wordpress.org/ticket/12696 - closed in favor of the next one
- https://meta.trac.wordpress.org/ticket/1278 - status: accepted, but nothing happening AT ALL, probably because: "That being said, I also don't see the point in implementing this until such a time that core or WordPress.org needs it (even though it'd be simple to do so)"

https://www.youtube.com/watch?v=sPHx5qPbWAc

cu, w0lf.

**Comment by senlin** [comment]
@nylen 

> We can't control what the WP directory does of course, but I think when we have our own plugin directory then a rule like this will make a lot of sense. @senlin can you post this over on https://forums.classicpress.net/c/plugins/plugin-directory please?

Here you go: 
https://forums.classicpress.net/t/plugins-whose-authors-do-not-update-them-should-be-removed/654

**Comment by nylen** [comment]
@ruiguerreiro sounds good to me, let's try it.

@ginsterbusch allowing sorting is a good idea for others ClassicPress directory, but in order to keep this issue focused, that suggestion should also go on the forums.

**Comment by ruiguerreiro79** [comment]
I just submitted the PR #342 
Need help to define the proper categories to display and the terms related to those categories.

It seems the API only accepts 1 tag in the search, maybe we can improve it to use multiple tags (this will mean multiple calls to the API) so a category browse like 'Social Networking' can use several tags like social, facebook, twitter.

Not sure if it's feasible for the V1.0 release

**Comment by tadatin** [comment]
Sorry for late join to the discussion, but I strongly advocate the "Favorites" tab and functionality in "Add Plugins" section. Reason - it is the quickest way to install own plugins collection anywhere in the world. Most unused and most valuable section of WordPress plugin installation window. I hope this functionality will remain.

Yes, now UI of this function implemented in the worst imaginable way, but when used once, it saves hours of time.
