### ISSUE TITLE
WordPress links at various files

### ISSUE THREAD

**Issue by stefanos82** [ClassicPress/ClassicPress#143]
As I have mentioned to @nylen in #140, I have checked with silver searcher `ag` and have found files that contain WordPress links.

Below I list _just a few_ of them and of course I'm pretty sure there are some that could be considered as false-positives, such as links inside comments and so forth; here's a portion of the list:

- tools/i18n/makepot.php
- Gruntfile.js
- tools/i18n/t/data/not-gettexted-0-result.php
- src/wp-includes/customize/class-wp-customize-nav-menu-locations-control.php
- src/wp-includes/customize/class-wp-customize-themes-section.php
- tools/i18n/t/data/not-gettexted-0.po
- src/wp-includes/class-oembed.php
- src/wp-includes/query.php
- src/wp-includes/shortcodes.php
- src/wp-includes/comment-template.php
- src/wp-includes/general-template.php
- src/wp-includes/theme.php
- src/wp-includes/nav-menu.php
- src/wp-includes/default-constants.php
- src/wp-includes/wp-db.php
- src/wp-includes/formatting.php
- src/wp-includes/deprecated.php
- src/wp-includes/class-wp-theme.php
- src/wp-includes/ms-load.php
- src/wp-includes/class-wp-editor.php
- src/wp-includes/js/mce-view.js

The list could go on...

**Comment by johnalarcon** [comment]
I'd prefer that URLs leading to specific documentation are left intact until there is a viable counterpart for any that get replaced. I do think they should all be replaced, but not if they will all be changed to reflect a single URL.

**Comment by stefanos82** [comment]
My ticket is not just for source comments, but for lines like the ones showed below:

https://github.com/ClassicPress/ClassicPress/blob/638d113ff5e4e928ff46c0c2cefca982d0d1b33f/src/wp-load.php#L80-L84

**Comment by johnalarcon** [comment]
Ah, yes, I see that now... Still, the distinction is: (from the initial issue description in #198)

> It's probably fine to leave codex URLs in place for now as these are more for self-help than Q-and-A, but those pointing to the WP forums should be updated.

The URLs I'm referencing in #198 are those that would lead users to places where they would be asking questions, which could be met with "resistance" from the WP support forum team. This issue is similar, just a different priority, IMHO.

**Comment by stefanos82** [comment]
> Below I list _just a few_ of them and of course I'm pretty sure there are some that could be considered as false-positives, such as links inside comments and so forth;

I think this answers your worry about the quoting above.

**Comment by nylen** [comment]
Ideally, issues/tickets are specific and actionable, so that someone can pick it up and finish it.  This isn't really the case with this one, since there are still some open questions like:

- How many different types of links / URLs are there that we need to update / change?
- Should these different types of links be handled the same way? (Almost certainly not)
- How do we know when we've found all of them?

So, I think both this issue and the more specific ones (#140 and #198 for example) are valid and useful.  We can think of this one as a "master issue" for all general discussion around remaining links to WordPress properties, and the more specific tickets like #140 and #198 can be used to plan, list, and knock out specific types of links.

**Comment by nylen** [comment]
One thing I'm not sure about is how to label / categorize "master issues" such as this one.  Thoughts welcome.

**Comment by stefanos82** [comment]
It would be great if GitHub had something like a thread feature for its issues. This way we could have a master issue as you have said and place the rest as its sub-issues.

**Comment by johnalarcon** [comment]
It can be created as a project, with these issues added as tasks.

**Comment by nylen** [comment]
I like the idea of organizing issues into parent issues (epics) and more specific issues nested under them (so far #140 and #198).

Creating a new project for this feels a bit heavy, but let's get a few more specific cases knocked out with issues / PRs and see how this is looking.

**Comment by stefanos82** [comment]
How about labeling each issue accordingly? For example, if an issue number 10 is the parent one, it should be labeled as such and any other issue that relates to it should be labeled as "related to issue-10" or something like that.

**Comment by nylen** [comment]
Don't love that either, because after using that system for a while we end up with a big mess of labels.  More things to curate and manage apart from actually doing the work or discussing it.

My favorite approach that I've seen so far is to update the original issue comment with a checklist.  Each list item points to an issue (if it exists), and they can be crossed off when they're done.

I really wish issues could have a "parent issue", and they would show up with some indenting and threading in the issues list.

In any case we need the specific issues first :wink:

**Comment by stefanos82** [comment]
Yep, that would work as well; I haven't thought of that to be honest with you.

Nice suggestion :+1:

**Comment by viktorix** [comment]
Thanks for reminding us. I've been thinking about it. Just haven't had any time to do anything with it yet.

I think the first step would be to replace all links in the core with a redirect link. So if we need to change where article points, we can do so easily without waiting on a core upgrade. 

The effort to rewrite some of the articles started but got stalled:
https://forums.classicpress.net/t/volunteers-for-writing-documentation/3483

**Comment by bahiirwa** [comment]
@viktorix Adding this here for followup. This link is broken. https://docs.classicpress.net/testing-classicpress/#reporting-bugs. How should we track these?

**Comment by viktorix** [comment]
All links will be updated in v2.0. This issue will be closed.
