### ISSUE TITLE
Brand Guidelines

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress#15]
Please refer to our brand guidelines page: https://www.classicpress.net/brand-guidelines/

I will be adding to it over the coming days and will also upload a resource of all the logos/images connected to the project.

**Comment by stefanos82** [comment]
A couple of observations:

- the logo is not clickable so I can go back to home page
- The `brand-guidelines` cannot be found anywhere in the menu bar.
- The forum is a subreddit. Why not take place here in GitHub Issues?

**Comment by danieltj27** [comment]
I'd much prefer the 'forum' to be on GitHub (here) too. Anything that isn't technically a bug/feature should get marked with a 'Discussion' label and closed after so long of inactivity to keep things fresh.

**Comment by stefanos82** [comment]
Even better; we could have a project under ClassicPress user, something like `https://github.com/ClassicPress/Discussions` and have there community discussions, brainstorming, tips and tricks, code hints, "did you know..." coding tooltips, and so forth.

**Comment by scottybo** [comment]
RE: The forum - one thing we have to remember is that not everyone who is contributing to ClassicPress is a developer. I chose Reddit initially for speed of getting something up and running (and also because a lot of people already use Reddit). Soon I'll be bringing everything under the ClassicPress, including community voting/disucussion, documentation etc. Happy to hear your thoughts on this :)

Thanks for the heads up on the logo and link - will get those sorted.

**Comment by stefanos82** [comment]
Thank you for letting me know @scottybo.

**Comment by nylen** [comment]
I'd keep the forum on Reddit, since the purpose of GitHub and Reddit is a bit different.

GitHub is best for organizing and completing (closing) specific, code-related technical tasks, with links to PRs etc.  An open issue has more of a connotation of something that is unresolved.

Reddit is better for general discussion, with more of a focus on sharing information and sorting topics by popularity / activity.

Trying to have general discussion on GitHub tends to get out of hand pretty quickly.

**Comment by scottybo** [comment]
Closing this issue as the topic is getting a little bit off track :)
