### ISSUE TITLE
Discussion: Collaboration between calmPress and ClassicPress

### ISSUE THREAD

**Issue by stefanos82** [ClassicPress/ClassicPress#164]
@markkap, the creator of calmPress has done an incredible job with his project and most of the changes he has applied to it could be of important use for ClassicPress as well.

My suggestion would be the following: we need to set up a common ground that could benefit not only these two projects, but also any other person or company is interested in forking WordPress for their own preferences and interests.

Think of this as a form of a lightweight `fooPress` framework that could play the role of a headless core that anyone could build on top of it, without deviating from its original schema.

Please bear in mind that this suggestion is for future versions of both projects, after they become solid, stable, and robust.

**Comment by markkap** [comment]
I truly do not mind, all the code of calmPress is in the open and obviously free to use, and if there is any clarification needed I will be glad to give (time permitting).

+1 for more organized collaboration if anyone has concrete suggestions on the "what" and "how"

**Comment by nylen** [comment]
We are open to ideas and collaboration as well.  I'll be able to give this some more thought and attention after our upcoming alpha release.

**Comment by wolffe** [comment]
If it's about stripping WordPress to more than 50% of its current codebase, I'm all for it. I was keeping an eye on both projects, as I am managing more than 50 small WordPress sites, which would definitely benefit from switching to ClassicPress.

+1000

**Comment by markkap** [comment]
@wolffe gladly both projects do not see eye to eye what belongs to core and what not as this difference can illustrate https://petitions.classicpress.net/posts/88/remove-the-theme-and-plugin-editors and https://github.com/calmPress/calmpress/issues/84

I say gladly, because if there was full agreement (or even just minor disagreements), one of the projects (probably calmPress ;) ) would have been a total waste of time.

Still there are a lot of things that can be standardized and code and knowledge can be shared like in how to support plugins and themes from outside of wordpress.org

**Comment by Mte90** [comment]
Looking at https://calmpress.org/difference-from-wordpress/ we are doing the same things (apart remove translations).
Many on https://petitions.classicpress.net/ requested to remove the stuff listed like WLH.
Anyway we will see because there is always space for collaboration between projects :-)

**Comment by senlin** [comment]
It's quite an impressive list he has there

**Comment by markkap** [comment]
I expect that there are going to be differences based on the response to the suggestion to remove the theme and plugin editors https://petitions.classicpress.net/posts/88/remove-the-theme-and-plugin-editors. 

I am sure that the path that calmPress takes will be somewhat extreme to casual WordPress developers taste, but whatever the differences are, there are so many issues WordPress core avoided handling over the years that there must be some common design and/or code that can be shared (installing plugin and themes fron let say github is just one example)

**Comment by nylen** [comment]
> installing plugin and themes from let say github is just one example

This is probably the biggest opportunity for collaboration that I can think of:  a non-WP.org plugin/theme directory.

Not something that we're going to start on right away, of course, but definitely something we're going to need as we get beyond v1.

Other than that, all of our code is open-source and GPL.  You're welcome to fork our [migration plugin](https://github.com/ClassicPress/ClassicPress-Migration-Plugin) and make it work with calmPress, for example.

Likewise, is there anything specific from calmPress that you think we might be especially interested in?

I see that calmPress is removing / deprecating a good number of features, mostly minor, but they may still be things that some plugins depend on.  What's your planned approach for ensuring that sites don't break along with these removals?

**Comment by markkap** [comment]
>  You're welcome to fork our migration plugin and make it work with calmPress, for example.

Was just thinking exactly about that ;)

> I see that calmPress is removing / deprecating a good number of features, mostly minor, but they may still be things that some plugins depend on. What's your planned approach for ensuring that sites don't break along with these removals?

Generally the answer is backward support for the relevant API signatures. It will most likely do nothing or return some kind of a "false" value depending on context.

... but many of the depredations are either UI related or are integration with 3rd party services, and they are being deprecated because they are just not useful. If there is some reasonable reason for anyone to still want to use the feature, it is better to make it a "core plugin".
Obviously this is "work in progress" and I am not sure yet how to handle the situation in which a plugin or theme tries to use functionality that was moved to a core plugin. Maybe detection if the core plugin is installed and issuing relevant error and admin notice if a relevant API is being used while it isn't.

**Comment by markkap** [comment]
As for plugin and theme repository, I was thinking more about being more aligned to how composer works, both to make the ability to install plugin more flexible and as a more distant goal, dependency handling. 

Discoverability, is something for which I havn't given enough taught yet, but I have a suspicion that most plugins are being discovered via google and not the plugin search in the admin install.
Maybe more than a repository which is just searchable for plugin names and description is good enough and there are already people that offer an alternative interface to wp.org, so this can not be too hard to do especially if you focus on the API and not on the UI.

**Comment by invisnet** [comment]
> Obviously this is "work in progress" and I am not sure yet how to handle the situation in which a plugin or theme tries to use functionality that was moved to a core plugin. Maybe detection if the core plugin is installed and issuing relevant error and admin notice if a relevant API is being used while it isn't.

Have a look at https://github.com/invisnet/ClassicPress/tree/v2

It's still very much a work in progress (not committed yet is theme dependencies) - we may be able to find some common ground.

**Comment by markkap** [comment]
@invisnet I see what you are doing there, but not sure it answer the situation in which someone is calling `is_customizer_preview()` from his theme code.

One possible solution is to keep the relevant API in core and move only the UI to a plugin. The one I was thinking about would have moved the API to a plugin and have something like 

if (function_exists('is_customizer_preview') {
  function is_customizer_preview() {
    admin_notice('Your theme is using customizer and you should install the core plugin to expose the relevant UI');
  }
}

The hard part will be to load such stub in the right place in the boot process, and what kind of message to issue when you are not in an admin context.

**Comment by markkap** [comment]
.... or you should implement the function under some other name in the core plugin, and than you can change the code of `is_customizer_preview` to check for the define and than call the function

**Comment by invisnet** [comment]
The customizer is a gnarly mess; I've code not yet committed that tries to unpick part of it, but it has its tentacles into so many areas - and with such bloody awful code - that it's way more work to sort out than it should be.
At this point I really don't know how best to deal with the customizer.

**Comment by markkap** [comment]
The good news is that weston ruter works now for google and unlikely to add more costumizer code

The bad news is that weston ruter works now for google which means that right now there is no one that can maintain that code :(

All WP JS code ended up as unmaintainable s**t. No idea why people think that the gutenberg JS will be any different.

**Comment by stefanos82** [comment]
> 
> Likewise, is there anything specific from calmPress that you think we might be especially interested in?
> 

@nylen This! https://github.com/calmPress/calmpress/issues/138

**Comment by Mte90** [comment]
Not an easy task but better open a petition about PDO so we can see how to do it.

**Comment by stefanos82** [comment]
@Mte90 Done. https://petitions.classicpress.net/posts/94/add-pdo-support

**Comment by stefanos82** [comment]
I was thinking: how about code-naming the common core foundations as **corePress**?

This way, people who are dissatisfied with WordPress's or even ClassicPress's direction and plan to fork, should not be forced to start stripping down their forked version until they meet their needs.

`corePress` should be the skeleton to build upon it and extend accordingly.

**Comment by BenOvermyer** [comment]
Probably not the best place to mention this, but seeing the comments about a central plugin/theme repository for both calmPress and ClassicPress, I'd volunteer to help with that effort.

**Comment by stefanos82** [comment]
@BenOvermyer it would be greatly appreciated if you could start participating in both projects to help them get their very first stable version out there.

**Comment by markkap** [comment]
@BenOvermyer From my POV (which is for now the calmPress POV ;) ) I do not actually want to manage a repository of 60k plugins and themes, but to be able to enable the user to use whatever repository he likes without the need to install additional plugins. Therefor standardization for me is more important than having actual repository.

Right now I am looking at how composer works to get inspiration.

But maybe this is the wrong issue to discuss details. I do not mind under which umbrella this is discussed, but if this is too early for ClassicPress to commit to such things we can do it over the calmPress repository or just set up a new repository for such effort just like FIG does IIRC.

**Comment by stefanos82** [comment]
> @BenOvermyer From my POV (which is for now the calmPress POV ;) ) I do not actually want to manage a repository of 60k plugins and themes, but to be able to enable the user to use whatever repository he likes without the need to install additional plugins. Therefor standardization for me is more important than having actual repository.
> 
> Right now I am looking at how composer works to get inspiration.
> 

We definitely need something like [packagist](https://packagist.org/), but for `corePress`, exclusively. This way it would be a lot easier to monitor themes and plugins for malware or insecure code, because they will have to apply specific standards and obey to certain rules in order to get accepted.

A repository would be another option too; it should work as expected as well.

**Comment by stefanos82** [comment]
I use Freenode IRC; we could create a temporary channel to chat in there, unless you have any other suggestion.

I use the same nickname.

**Comment by BenOvermyer** [comment]
While IRC is good, somewhere that has a written record would be better, since this impacts the community.

Maybe a separate GitHub organization `corePress`? Could start a repo just for discussions, or something.

**Comment by stefanos82** [comment]
@nylen @Mte90 @markkap suggestions?

**Comment by nylen** [comment]
Well, there is much more interest in going ahead and setting up a plugin repository than I thought.  So let's get that moving, I think it would be great for people to start on that while ClassicPress is mostly busy preparing for a v1 release.

There has also already been some discussion around this project on ClassicPress Slack, so we need to go ahead and get some thoughts & links to resources out there in a more persistent form that people can use to build on top of.  This issue is not really the best place to do that either.

> I prefer to keep it in the open and best place is github

Agreed.  To the extent that ClassicPress is "officially" involved here, there will probably still be some chatter on our Slack group, because coordinating with more real-time discussion is still helpful, but let's keep as much of the work as possible tracked & discussed on GitHub.

So there are a couple of options.

1. Create a new `corePress` org.
2. Have this live under `ClassicPress`.
3. Have this live under `calmPress`.

I am fine with any of those really, at the end of the day the substance and quality of what we ship matters more than what it's called, and the result will hopefully be the same.

But, thinking longer-term, a good goal for this effort is to create a common repository that calmPress and ClassicPress can share, and allow for other such projects in the future, so (1) is probably the best choice.

> From my POV (which is for now the calmPress POV ;) ) I do not actually want to manage a repository of 60k plugins and themes, but to be able to enable the user to use whatever repository he likes without the need to install additional plugins. Therefor standardization for me is more important than having actual repository.

We probably wouldn't start by importing all 60k projects from WP, but to me this also means that putting the repository under `calmPress` doesn't make as much sense.

**Comment by nylen** [comment]
Also some discussion about plugin repositories at #46.

**Comment by markkap** [comment]
corePress is probably best, @stefanos82 since you suggested it, do you mind setting up such a repository?

**Comment by stefanos82** [comment]
@markkap I don't mind. I could also create a `corePress` org and place it under its own repository as well, but I will need some help around this as I have never done such thing before.

**Comment by stefanos82** [comment]
@markkap done. Both org and repo are on.

Let me send you an invitation.

**Comment by stefanos82** [comment]
Whoever is interested in participating in `corePress` org and repository for further discussions, please let me know.

The org is https://github.com/corePress/ and the actual repo is https://github.com/corePress/corePress

**Comment by nylen** [comment]
We're probably going to want more specific `corePress` repositories pretty quickly, rather than lumping everything under one repo.  I'd suggest renaming that one to `corePress-discussion` if that's the purpose of that repo.  Then the first "non-discussion" repo that we create would be `corePress/open-directory` or something like that.

**Comment by BenOvermyer** [comment]
I very much approve of that path, @nylen .

**Comment by nylen** [comment]
@stefanos82 what do you think about renaming `corePress/corePress` to `corePress/corePress-discussion`, per the above?

**Comment by nylen** [comment]
After that, I think we can actually close this issue and point to https://github.com/corePress as the official place for collaboration between calmPress and ClassicPress.  :100:

**Comment by stefanos82** [comment]
@nylen Mission renaming: accomplished.

Let's keep the spirit high people, I'm happy ^_^

**Comment by nylen** [comment]
Thanks everyone! See you over at `corePress`!
