### ISSUE TITLE
Potentially user-facing support URLs in core are pointing to WP properties

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#198]
Recently submitted issue #195 and then PR #196 to update support URLs in the dashboard, but found there are several other places in core that have similar URLs pointing to WP properties. It's probably fine to leave codex URLs in place for now as these are more for self-help than Q-and-A, but those pointing to the WP forums should be updated. I'll submit a PR once it's decided which URLs to use.

## Expected behavior
User-facing support URLs in core point to CP properties.

## Current behavior
Some URLs point to CP properties.

## Possible solution
Update those URLs.

## Steps to reproduce (for bugs)
Searching core for '/forum/'.

## Context
Branding, identity, user support.

https://github.com/ClassicPress/ClassicPress/blob/638d113ff5e4e928ff46c0c2cefca982d0d1b33f/src/wp-admin/includes/class-wp-automatic-updater.php#L835-836

https://github.com/ClassicPress/ClassicPress/blob/638d113ff5e4e928ff46c0c2cefca982d0d1b33f/src/wp-admin/includes/ms.php#L996-L997

https://github.com/ClassicPress/ClassicPress/blob/638d113ff5e4e928ff46c0c2cefca982d0d1b33f/src/wp-admin/maint/repair.php#L147

https://github.com/ClassicPress/ClassicPress/blob/638d113ff5e4e928ff46c0c2cefca982d0d1b33f/src/wp-admin/network/index.php#L50-L51

https://github.com/ClassicPress/ClassicPress/blob/638d113ff5e4e928ff46c0c2cefca982d0d1b33f/src/wp-admin/network/site-new.php#L30-L31

https://github.com/ClassicPress/ClassicPress/blob/638d113ff5e4e928ff46c0c2cefca982d0d1b33f/src/wp-admin/network/sites.php#L42-L43

https://github.com/ClassicPress/ClassicPress/blob/638d113ff5e4e928ff46c0c2cefca982d0d1b33f/src/wp-admin/network/user-new.php#L26-L27

https://github.com/ClassicPress/ClassicPress/blob/638d113ff5e4e928ff46c0c2cefca982d0d1b33f/src/wp-admin/network/users.php#L179-L180

**Comment by stefanos82** [comment]
It's related to my ticket #143

**Comment by stefanos82** [comment]
Well, not exactly. It's not just source comments; there are many places where `__(...'wordpress.org'...)` can be found, that's why I have opened the aforementioned ticket.

**Comment by nylen** [comment]
There are a couple of different URLs listed here: **support forums**, **report a bug on Trac** and **codex documentation pages**.

- **Support forums** - the right place to point this to right now is https://docs.classicpress.net/faq-support/.  Right now we just have a `#support` channel in Slack, but I also like this solution because we can update that page later when we get our own support forum.
- **Report a bug on Trac** - This can link to https://docs.classicpress.net/testing-classicpress/#reporting-bugs
- **Codex documentation pages** - I think we can just leave these alone for now.  We're focusing on quality over quantity for our initial documentation efforts, and almost all WP documentation will still apply to ClassicPress for the entire v1 release series.

**Comment by johnalarcon** [comment]
I'll write a PR for those first 2 bullet points today.

**Comment by johnalarcon** [comment]
PR #200.

**Comment by johnalarcon** [comment]
PR #200 merged; closing this.
