### ISSUE TITLE
The future of ClassicPress and its direction

### ISSUE THREAD

**Issue by danieltj27** [ClassicPress/ClassicPress#22]
I think there needs to be an honest and frank discussion around the direction of ClassicPress and where's it's actually heading right now because I don't believe that the current roadmap makes room for the changes that need to occur to make this a successful fork.

For example;

* The website still promotes the petition. Gutenberg is happening and it's not going to stay as a plugin, it will be merged at some point in time. This sends very mixed messages to visitors of the site.

* Changes to WordPress proposed to be merged in ClassicPress. ClassicPress is supposed to be a fork, which generally should branch off the current release and go in a different direction. If ClassicPress is going to stay in sync and 'up to date' with WordPress minus the Gutenberg bits, then really there's no point in the fork because you could arguably just use the Classic Editor plugin or not update to 5.0. ClassicPress won't offer anything inviting for users to switch. It becomes moot.

* There was some talk about having two ClassicPress versions. Again, there should be one version that branches off WordPress and goes it's own way. Having two versions that are mostly similar, even in the short term will create much confusion and won't give users a proper gateway to switching over.

I think that generally, there needs to be a clear and definitive path forward in order for this project to work and be successful. I'd be keen to hear thoughts on this and ideas about what the next steps are. I'd rather keep this off Slack as it's an issue that should have some GitHub history (plus I don't want to signup for _yet another_ Slack workspace just yet).

**Comment by scottybo** [comment]
Some very good points.

My primary goal right now is getting ClassicPress v1.0.0 out the door with a migration plugin. I completely agree there needs to be a roadmap and that we need to be clear that in the long term we're going to be more than just a fork without Gutenberg.

The biggest resource I lack right now is time. I'm not going to get my tiny violin out, but there is an enormous amount of back office stuff going on right now. In essence, launching ClassicPress is no different to launching a new business, complete with registering a Limited by Guarantee company (which I did on Saturday) and setting up a bank account so we can legitimately accept donations and start fund raising to cover costs for tools such as Trello.

There is a lot that I want to change on the website - from typos to removing the petition and adding a collaborators page.

I'm all ears about how we move forward and am very happy to take your advice and the advice of other collaborators on what we should do next.

**Comment by KTS915** [comment]
I agree with everything that @danieltj27 said. I would be happy to commit a ton of time to ClassicPress (including its website) if I could be sure that it is going to move in a worthwhile direction, but it is difficult to get behind a project until some sort of vision has been articulated.

Although I haven't joined the CP Slack channel (again for much the same reasons as @danieltj27), it seems to me that many of the people who are interested in it are ones who (like me) have repeatedly argued that WordPress should concentrate on providing a lean, fast, secure core with useful APIs that allow other developers to build out sites with appropriate plugins. This would mean removing quite a bit of cruft that WP currently includes. If that is the direction that CP will be aiming for, then I'm all in.

If, on the other hand,CPt is going to be focused on keeping 4.9.8 working for _n_ years, then I don't really see the point.

I absolutely do appreciate all the hard work that must be done behind the scenes to even get a fork off the ground. I am sure that that is why, despite several years of disquiet, no-one has been brave enough to attempt to do this before. And, since I don't have the technical expertise to help out with that, I am very interested in taking on some of the burden in other areas. But, before I do that, I really need to see some indication of the broader goals for CP, and not just in terms of decision-making process.

**Comment by scottybo** [comment]
I hear you - and I'm going to push this back onto you. What do YOU think the goals should be? 

This is a community led project - I'm just the person facilitating it. That is pretty much THE goal of ClassicPress - the direction it takes is up to the will of the community.

**Comment by danieltj27** [comment]
I understand the reasoning and since earlier I've joined the Slack channel and have had a look through the discussions to try and get an idea of the direction and roadmap of the project going forward. I think I'm going to take a step away from ClassicPress, at least for now and focus on my own blogging project that I've been working on for a number of weeks now.

I genuinely do wish the project the best of luck though as it'll be difficult to push forward and I don't want to come across as 'jumping ship', but with other commitments, I don't think this is quite the right project for me to attribute my time to.

I think it'll be interesting to step aside from it for a while and just observe and see what happens. There's so much uncertainty with WordPress itself that it's difficult to comment on what the best way forward is I believe. As I started it off, I'll close the issue but if needs re-opening then feel free.

**Comment by KTS915** [comment]
Reopening so as to reply to @scottybo's perfectly reasonable question: "What do YOU think the goals should be?"

As I said earlier in this thread, I think CP should aim to provide a lean, fast, secure core with useful APIs. To that end, here are some fundamental principles that (subject to comment from and critique by others) I think should be part of CP's guiding philosophy:

**1. Security is a prerequisite for everything we do.**
This isn't true of WordPress. For example, a security vulnerability existed because WordPress does not enable strict mode for MySQL. If STRICT_ALL_TABLES has been enabled, this would have fixed the problem. But (until Gutenberg) WP prioritized backwards compatibility, and so came up with the bizarre "fix" that meant including all the nonsensical emoji guff.

CP should announce a clear departure from that approach at the outset. CP will make a potentially-breaking change if it is necessary to maintain security. (This also means, of course, dropping support for versions of PHP that no longer receive security updates.)

**2. CP should prioritize function over form.**
No more of the narrow window nonsense seen in the Customizer and Gutenberg. CP's job should be to enable stuff to work. It should be up to theme designers to make it look good. That also leads to (3) ...

**3. CP should focus on the back-end, and leave the front-end to themes and plugins.**

**4. As (2) and (3) imply, CP should avoid competing with plugins unless best practice has clearly emerged and it would be simpler just to build it in.**

**5. CP should typically add functionality by developing APIs, though these should have proper on-off switches and will often need to be off by default.**
The REST API is a classic example of a great API but one that should never have been turned on by default. Even its lead developer did not support that decision.

**6. Document, document, document!**
Much of WordPress is well documented. But some is hardly documented at all, and this is particularly true of anything to do with JavaScript, like Backbone.js or the REST API. This is a serious failing and one that CP should do its utmost to avoid replicating.

**Comment by nylen** [comment]
Hi @KTS915, in general I really like the way you are thinking about this.

Regarding security: Being a new project, we have a number of opportunities that WP won't have. For example, this definitely needs more research before making a decision, but for new installs especially, it shouldn't cost us much to enable strict tables.

>CP should announce a clear departure from that approach at the outset. CP will make a potentially-breaking change if it is necessary to maintain security.

When we do this, we need to be sure to communicate breaking changes clearly to potentially affected users, and introduce them in a new major version, follow semver, etc. Where possible, we should automatically detect whether a change is going to cause problems on a site.

It's also important to differentiate between **short term** and **long term** goals of the project.

In the short term, there is a lot of uncertainty about the future of the WP classic editor. The WP 4.9 branch will probably be supported for a long time, but beyond that:

- Will it be publicized and encouraged as an option for people who can't use Gutenberg for whatever reason?
- What will upgrade prompts to 5.x look like? Will they transparently inform the user about the major changes?
- The Classic Editor *plugin* is supported, but for how long? How long until it accidentally breaks because people aren't paying attention?

So, this is the first and earliest way that ClassicPress can offer value: "Remember that platform you liked? Sure, it's not perfect, but we kept it working for you."

In the medium term, we should be looking to build solid foundations for new features. Imagine all the things we (and plugin authors) could build if the custom fields API had been part of the core platform and had been supported, tested, and extended to support rich content for several years.

Longer-term... I'm not really sure what our plans can look like. It's a bit hard to predict, because before we can really plan steps 2-10 we have to do step 1 first, which is put together an initial release with working migration from WP and working upgrades.

That, in itself, is a ton of work. That's where my focus will be initially.

Still, this is a good discussion to be having, so I'm going to leave this issue open. Thanks @danieltj27 for starting it.

**Comment by KTS915** [comment]
> It's important to differentiate between short term and long term goals of the project.

While that might often be true, it's a bit of a red herring here. The only short-term goal should be to get ClassicPress into a state where it can be uploaded to a live website and put into use.

In particular, I don't agree that there is much value in the proposition: "Remember that platform you liked? Sure, it's not perfect, but we kept it working for you." Anyone can get precisely the same "value" just from not updating WP at all. Indeed, that's what I had planned to do before CP was mooted. WP provides security updates for past versions, so that wouldn't cause a problem.

The value that CP should be offering is in restoring a relationship of trust between those working on the code and those using that code. The decision-making goals that @scottybo has already articulated make it plain that that was his focus. But while they are certainly prerequisites to achieving that goal, they aren't enough on their own. Users need to know where the CP project is heading before they commit to moving to it.

So the longer-term goals are actually vital in informing even short-term decision-making, at least for those (like me) thinking about getting involved with CP or using it on their own sites. And the specific points that I set out above would demonstrate in a practical way precisely why CP is a trustworthy project.

> Being a "new" project, we have a number of opportunities that won't come as easily to WP.

I agree 100%. So we have to make it clear from the outset which of those opportunities we plan to take.

> When we do this, we need to be sure to communicate breaking changes clearly to potentially affected users, and introduce them in a new major version, follow semver, etc. Where possible, we should automatically detect whether a change is going to cause problems on a site.

I agree again. But that also means that we should make it clear to everyone from the very beginning of CP's existence.

> In the medium term, we should be looking to build solid foundations for new features. Imagine all the things we (and plugin authors) could build if the custom fields API had been part of the core platform ...

I have already made clear that I support the idea of developing useful APIs. But your notion of there being a (more defined) "medium term" and then a later (undefined) longer term really concerns me. That suggests that core CP devs get to choose first, and then we'll wait and see. Both elements provide a recipe for non-engagement. Why should core devs go first? And why should I use/get involved with CPO if I have no idea where it's headed?

Instead, everything after the initial phase of making CP functional should be addressed by articulating a core philosophy that creates expectations for potential contributors and users of where the project is heading.

**Comment by danieltj27** [comment]
I agree with @KTS915 here. I feel the need to chime in again to reiterate the importance of the above comment because I really do want ClassicPress to succeed because even if I never use it, a community led fork would do the world of good for giving people a choice of what they want in their CMS.

The issue I have, and I'm not here to cause difficulties, is that there needs to be one clear vision going forward and the first step is to create a new repository and push 4.9.x (whatever the last version is before 5.0) and then begin renaming everything from WordPress, WP, wp etc to ClassicPress... and so on. That must happen first.

There shouldn't be any talk of swag, a service like .com or anything other than prepping WordPress core for a fork and then branching off entirely. Another thing that has been mentioned before is '_WordPress without Gutenberg_'. Bear in mind that WordPress 4.9.8 (minus the callout message) *_has no Gutenberg_* and is easily '_Guten-free_' by way of a simple hook to remove the callout and not updating to 5.0 or using the Classic Editor plugin.

Even when/if Gutenberg lands in WordPress 5.0, Gutenberg won't have 'taken over' the WordPress experience just yet, so even then you're still able to easily 'free yourself' from Gutenberg. So again, ClassicPress doesn't off anything different so to speak in that regard. The edge that ClassicPress has is to branch off early and focus on lots of bug fixes, improving the APIs and tidying things up. The issue the project will face early on if this doesn't happen is possibly a 1 or 2 commit step behind actual WordPress so user's will only gain an outdated product.

Again, **I want ClassicPress to succeed** because if nothing else, a fork of WordPress would be a great way to make changes to core in a unique and unseen way up until now. It'd give users more choice and also be a way to really see what matters to the community if things are community led. Having a committee of people decide circles back to having a small core team that make all the calls and removing the voice from the wider community.

The first thing that needs to happen is to decide - and this is probably up to @scottybo  - is to think about whether 4.9.8 is the right version to fork, or to wait until the version right before 5.0. Then, work should begin on stripping out anything 'WordPress' and renaming things until there is a ClassicPress which is ready to be actively worked on. The project was started a number of weeks ago and we still don't have a proper codebase to work from yet. That should be the first priority I feel.

**Comment by scottybo** [comment]
@danieltj27 I appreciate your candor - would you be open to joining our committee? I've heard your feedback and have taken it on board. The committee is being formed to make these decisions for the good of ClassicPress and your opinion/input would be highly valued.

**Comment by scottybo** [comment]
@KTS915 thank you for your input, these points are excellent.

@nylen has asked if we could also invite you to the committee. Would you be open to the idea?

**Comment by nylen** [comment]
> The first thing that needs to happen is to decide - and this is probably up to @scottybo - is to think about whether 4.9.8 is the right version to fork, or to wait until the version right before 5.0. 

Just as a technical note, this is not necessary. This is one reason that we will be merging relevant changes and fixes from WP. Another is that there will be fixes coming through that are valuable in themselves.

Later on, if we end up diverging from WP, trying to incorporate changes may not be so useful, but for now, it is the right choice.

**Comment by senlin** [comment]
So if that is the case, when can we actually start doing something, like for example start with #3 ?

**Comment by danieltj27** [comment]
Thanks for the responses to my questions.

As for the committee invitation, let me have a think about it and I'll get back to you soon. I'd like to spend some time considering whether or not I'd be able to set aside enough time to make an impactful contribution or not. As I've mentioned, I'm currently working on my own project and want to dedicate enough time to getting that in a shippable state too of course.

**Comment by invisnet** [comment]
I think CP still needs a clear vision; yes, having a rotating committee will prevent a repeat of Gutenberg, but without a clear vision it will devolve into design-by-committee (e.g. the duck-billed platypus).

WP has completely departed from "lean and mean" - that's where CP could shine.

Think of it in terms of the age-old debate about monolithic kernels vs. microkernels. If CP were a microkernel - move everything possible into plugins - it would solve two problems in one go:

1. refactoring the core would become _much_ easier,
2. the committee would have a test to apply to new features

It would also give possible contributors (like me) who are now just watching and waiting a better idea of whether they want to get involved.

**Comment by scottybo** [comment]
@invisnet we're still in the founding stages - we **need** people like you to jump in and get involved. I'm just the person who has taken the plunge with starting this project. Your ideas are fantastic and they should be discussed.

I'm not sure how to stress this any clearer: **I need your help**. I'm just the lunatic who decided to take the plunge with this fork. I started with an idea and it has now taken on a complete life of its own.

As such, the vision should be decided by the community, not me - I would like people to share their ideas and thoughts, debate them and then as a community decide our way forward. 

I need people to step up to the plate and take a risk, to say "Yes, I'll be on the committee" and help shape the direction we go. I don't know what the future holds, but I know that we need to decide how we get there together.

**Comment by KTS915** [comment]
@scottybo, yes, I would certainly be open to being on the committee. Just let me know where and when you want me, or how I should contact you.

**Comment by scottybo** [comment]
Closing this issue as I think it's clear we have a future and a vision :)
