### ISSUE TITLE
Naming schema needed for brand assets (images, logos, etc)

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#266]
There seems to be a few naming schemas emerging for brand assets, such as logos. I'd like to see a consistent schema decided that will allow for consistency, better predictability, and improved image-search SEO.

## Expected behavior
A consistent, explanatory filename schema for brand assets.

## Current behavior
Brand assets are inconsistently named. For example, in the `./wp-includes/images/` directory, I find the following filenames, which also point out need to standardize capitalization.
* ClassicPress-icon-blue-600.png
* classicpress-logo-dashicon-style.svg

...then, from the [brand assets page](https://docs.classicpress.net/press-and-branding/), there's the following filenames:

* feather-gradient.svg
* feather-white.svg
* icon-gradient-600.png
* icon-gradient.svg
* icon-white.svg
* logo-gradient.svg
* logo-white.svg
 
## Context
The brand assets page has probably the most-aligned filenames (to one another, not the project). However, the filenames have no context outside of that page. If they are named according to a defined schema, we can ensure they always have context, in any context. This may also help with SEO in image searches. The brand assets page should be first result for a search for the CP logo; resolving this issue will help.

## Possible solution
Leave any existing images in place to avoid breaking changes with plugins/themes that may be using them. Introduce newly-named images and use those going forward with a naming schema such as the following:

> brand-purpose-type-color-wxh.ext

```
Coin Logotype
classicpress-logo-coin-green-50x50.svg
classicpress-logo-coin-white-50x50.svg
classicpress-logo-coin-green-50x50.png
classicpress-logo-coin-white-50x50.png

Feather Logotype
classicpress-logo-feather-green-50x50.svg
classicpress-logo-feather-white-50x50.svg
classicpress-logo-feather-green-50x50.png
classicpress-logo-feather-white-50x50.png

Wordmark Logotype
classicpress-logo-wordmark-green-300x50.svg
classicpress-logo-wordmark-white-300x50.svg
classicpress-logo-wordmark-green-300x50.png
classicpress-logo-wordmark-white-300x50.png

Icon/Dashicon/Favicon, et al
classicpress-logo-icon-green-20x20.png
classicpress-logo-dashicon-green-20x20.png
classicpress-logo-favicon-green-20x20.png

```
**Notes**
1. The above size/dimension values were made up.
2. The word 'gradient' is omitted; every colored logo has gradient.
3. Adding a size value to svg images isn't necessary, but consistency is nice.

**Comment by bahiirwa** [comment]
Agree with convention suggested.

**Comment by johnalarcon** [comment]
See also: https://forums.classicpress.net/t/docs-for-brand-assets/476

**Comment by nylen** [comment]
Good idea.  A few notes:

- There are some filenames we'll need to leave as-is because they were included with WordPress.  We can rename anything we've added afterwards though.
- I don't think the `color` value makes sense as-is.  Which color is it referring to?  Most of the images marked as `green` and `white` actually contain both colors.  Might be better to specify whether the color is referring to the background or foreground, e.g. `classicpress-logo-coin-bg-green-600.png` or `green-on-white`.

Once we come up with something we're happy with here, we can update the Press & Branding page to be aware of these conventions and serve a couple of different formats/sizes for each image.

**Comment by johnalarcon** [comment]
>     * There are some filenames we'll need to leave as-is because they were included with WordPress.  We can rename anything we've added afterwards though.

Agree; noted in original PR "Possible solution" section.

>     * I don't think the `color` value makes sense as-is.  Which color is it referring to?  Most of the images marked as `green` and `white` actually contain both colors.  Might be better to specify whether the color is referring to the background or foreground, e.g. `classicpress-logo-coin-bg-green-600.png` or `green-on-white`.

It's the predominant color, but I see your point. If I had to choose between one or the other of the suggestions, it would be the one with the _bg_ added. I wouldn't title it like a yoda condition, though. Instead, I'd do `classicpress-logo-coin-green-bg-600x200.png`.

**Comment by johnalarcon** [comment]
Can we call this decided? What can I do to get this moving?

**Comment by invisnet** [comment]
I can't see a reason not to do this, and if we're going to include the image size in the filename we should include both dimensions - all or nothing on that.

**Comment by nylen** [comment]
>if we're going to include the image size in the filename we should include both dimensions

OK by me.  Though the dimensions should be left off of the SVG images still, as they don't have a defined resolution.

I took a closer look and we are talking about renaming or removing 4 files here:

```
src/wp-admin/images/cp-logo-gradient.png
src/wp-admin/images/cp-logo-gradient.svg
src/wp-includes/images/ClassicPress-icon-blue-600.png
src/wp-includes/images/classicpress-logo-dashicon-style.svg
```

I started working on this and realized we do need both the FG and the BG colors, otherwise there will be some filenames that won't fit.

> <img src="https://user-images.githubusercontent.com/227022/52982906-9a760100-33b6-11e9-857e-bcf860e02f2d.png" width="400">

These are both valid, and they differ only in the foreground color:

```
classicpress-logo-wordmark-gradient-on-transparent.svg
classicpress-logo-wordmark-white-on-transparent.svg
```

So, with that in mind, please take a look at PR #366 and make sure the changes look OK.
