### ISSUE TITLE
Hide WP default themes from Themes page

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress#299]
Following issue #291 (Theme footers show "Proudly Powered by WordPress") and the PR #292 to add child themes of the WP default themes, the next step now is to hide the WP default themes from the Themes page in the Dashboard.

The exception is that if a WP default theme (Twenty Fifteen, Sixteen or Seventeen) is active, it cannot be hidden. 

With this issue we can properly investigate on what is the best way to accomplish this.

**Comment by senlin** [comment]
Had some time to dive into this.

In `src/wp-admin/themes.php` [the theme page is being built](https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-admin/themes.php#L250) using a `foreach` loop. 

Unfortunately I have no idea how to exclude the twentyfifteen, twentysixteen and twentyseventeen `$theme`s from that loop, so the page can be generated without them.

Any help or tips, are welcome.

**Comment by mattyrob** [comment]
@senlin 

This code snippet should help you hide themes from the Theme menu:

```
function clean_themes( $themes ) {
	unset( $themes['twentyten'] );
	unset( $themes['twentyeleven'] );
	unset( $themes['twentytwelve'] );
	unset( $themes['twentythirteen'] );
	unset( $themes['twentyfourteen'] );
	unset( $themes['twentyfifteen'] );
	unset( $themes['twentysixteen'] );
	unset( $themes['twentyseventeen'] );
	unset( $themes['twentyeighteen'] );
	unset( $themes['twentynineteen'] );
	unset( $themes['twentytwenty'] );

	return $themes;
}
add_filter( 'wp_prepare_themes_for_js', 'clean_themes' );
```

**Comment by senlin** [comment]
@mattyrob 

Thanks for the snippet. What exactly does this do?

The reason I ask is that the ClassicPress TwentyFifteen, ClassicPress TwentySixteen and ClassicPress TwentySeventeen are child themes of their resp. WP counterparts and therefore should remain accessible.

We need to hide them from the eye except of course if it the active theme.

**Comment by mattyrob** [comment]
@senlin 

This filters the array of available themes and unsets some we may not want. I guess you can get cleverer in the function and check for the active theme and ensure that remains set - I'm not sure what would happen with child themes.

**Comment by senlin** [comment]
@nylen as I said above: [L250 in themes.php](https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-admin/themes.php#L250) is where the magic happens, only I cannot do anything with it.

**Comment by mattyrob** [comment]
@nylen @senlin 

The code snippet above filter the WordPress array of returned themes and it does work in the Appearance > Themes page and the Appearance > Customizer pages. It doesn't work in the Theme Editor page.

The files remain in place on the server, it is just the array of available themes that is changes.

If changes are wanted in the core then you'd need to `unset` the array keys locally in the themes.php file prior to the `foreach` loop.

**Comment by ruiguerreiro79** [comment]
In this case I guess we can unset them here [https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-admin/includes/theme.php#L622](url)

It seems to work fine.
![image](https://user-images.githubusercontent.com/29898220/51621222-f53d4980-1f2b-11e9-9160-5ffb7dc72bd6.png)

**Comment by ruiguerreiro79** [comment]
I can implement this, we just need to be careful to don't unset the active theme right?

**Comment by nylen** [comment]
Yes @ruiguerreiro79 that's right.

**Comment by nylen** [comment]
It might also be a good idea to add a link that says "N themes hidden, click here to show them".

**Comment by ruiguerreiro79** [comment]
@senlin No problem at all. 
@nylen My estimate is to deliver this till 30 of January

**Comment by nylen** [comment]
@ruiguerreiro79 let's leave the `help wanted` label on this until you start working on it.  If someone is able to start on it before you can get to it, I think that's fine.

**Comment by ruiguerreiro79** [comment]
I was implementing a solution for this issue but during that implementation some concerns arrise.

This was my approach to the problem.
![image](https://user-images.githubusercontent.com/29898220/52589109-f5977900-2e35-11e9-8b9f-c9920f425f9b.png)

My concerns are:

1. The parent customizer options like the Additional CSS field
2. The menu locations assignment.
3. Widgets assigned.

If someone deactivates  by any reason the official Twenty Seventeen to troubleshoot a problem, after that deactivation it won't be possible to activate that theme again since the TwentySeventeen will disapear from the list.

Activating the child theme of Twenty Seventeen won't  return the site to the previous state since all the 3 points above will be gone since they have their options related to the child theme and not the parent theme.

Guess the way to avoid this is to create a migration process that will run once of the settings (3 points above) of the parent theme to the child theme.

any

**Comment by nylen** [comment]
> If someone deactivates by any reason the official Twenty Seventeen to troubleshoot a problem, after that deactivation it won't be possible to activate that theme again since the TwentySeventeen will disapear from the list.

**Comment by ruiguerreiro79** [comment]
@nylen 
Regarding the change itself that is a centralized function wp_prepare_themes_for_js() that is used by that ajax call and the themes.php.

I will add that link that states that some themes are hidden and when you click on it the page will have to refresh passing a specific param so that we can ignore the exclusion.

Yes, I agree that the migration process is too much work for now.

**Comment by nylen** [comment]
Removing the milestone, a fix for this is still welcome but it's going to stay as-is for 1.0.0-rc1 and 1.0.0.

**Comment by nylen** [comment]
This has come up again during the RC period ([link](https://forums.classicpress.net/t/rc1-download-includes-classic-editor-and-extra-themes/860)), and I still don't think it's a great experience the way it is right now either.  #385 is another idea for what to do about it.
