### ISSUE TITLE
Problem with creating new install in Russian

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/ClassicPress#323]
After setting up a new install in Russian, the theme editor does not function.

## Steps to reproduce
1. Install CP.
2. Select core_RU in general settings
3. Almost all the parts of CP will be in Russian, but theme editor is broken.

It is currently resolved by a manual install of translation files from https://make.wordpress.org/polyglots/teams/

Reference https://forums.classicpress.net/t/a-new-cp-installation-is-broken/557

**Comment by Mte90** [comment]
seems related to https://github.com/ClassicPress/ClassicPress/issues/319

**Comment by nylen** [comment]
Fixed in https://github.com/ClassyBot/i18n-scripts/pull/1 and https://github.com/ClassicPress/ClassicPress-Network/pull/29.

If your site is affected by this issue, you'll need to select your desired language in the settings and save the changes.  See https://github.com/ClassicPress/ClassicPress-Network/pull/29#issuecomment-452553941 for details.
