### ISSUE TITLE
Shortcodes containing asterisks may create invalid regex breaking the editor

### ISSUE THREAD

**Issue by Vusys** [ClassicPress/ClassicPress#345]
Despite not being a reserved character an asterisk in a shortcode followed by another character will generate invalid regex which breaks the editor.

This code reproduces the issue:

```php
<?php
add_shortcode( '*stars*', function() {
	return '★★★';
} );
```

Below is a gif showing the editor tabs not working correctly along with the error in the console in Chrome 65 and Firefox 59.

![2018-04-03 22 30 25](https://user-images.githubusercontent.com/4213522/51794386-e4116880-21c9-11e9-9a7e-c00ca6a221c1.gif)

I know it's unconventional to use an asterisk in a shortcode, but my use case is porting a legacy CMS that used BBCode into WordPress while trying to keep as much of the original formatting possible for old content.

This is an issue with all plugins deactivated (except for the above code) using the Twenty Seventeen theme.

This was originally reported on the [WordPress trac](https://core.trac.wordpress.org/ticket/43686).

## Expected behaviour

Editor should allow shortcodes containing an asterisk

## Current behaviour

Invalid javascript is generated which breaks the editor

## Possible solution

https://core.trac.wordpress.org/attachment/ticket/43686/43686.diff

**Comment by nylen** [comment]
Thanks for the clear & detailed bug report.  This makes sense to me, but I'd like to see the bug and the fix proven with an automated test.

There is already a JavaScript testing structure set up for ClassicPress, it works the same as the corresponding code for WordPress: https://make.wordpress.org/core/handbook/testing/automated-testing/qunit/

In general the best way to fix an issue like this is to use [test-driven development](https://en.wikipedia.org/wiki/Test-driven_development):

- Start a PR with only a failing automated test case (this will show up on the PR as a red :x: when the [Travis CI](https://travis-ci.org/) build fails)
- Push the fix in a separate commit to the same PR
- Verify that the automated test now passes (the build indicator should change to :heavy_check_mark: on the PR)
- Even more bonus points for testing other special characters and verifying the fix for them too.

This kind of development workflow achieves several things at once:  it makes the change easy to review (whoever is reviewing it, most likely me for now, can immediately verify the bug and the fix), and it ensures that this bug can't ever resurface again.

**Comment by joyously** [comment]
This page https://codex.wordpress.org/Shortcode_API#Names
lists the characters that should not be in a shortcode name. Although the asterisk is not listed, it should be.
