### ISSUE TITLE
Redesign the 'user' dropdown in admin bar

### ISSUE THREAD

**Issue by PointandStare** [ClassicPress/ClassicPress#349]
Glad we got rid of 'Howdy' but now I suggest changing this area to something more useful.

## Expected behavior
Fast link to My Profile information.

## Current behavior
Currently my user name is posted in this area twice.
Listed as 3 links to 'My profile'.

## Possible solution
As the top level is a rollover (to reveal) change wording to 'My Profile'.
On rollover reveal these anchored links:
- Change avatar (if possible)
- Change password
- Log out

So, you can directly go to either 3 (most used) sections.

## Steps to reproduce (for bugs)
1. Open Admin
2. Cursor top right, rollover username

## Context
This area seems like an after thought - either remove completely or make more useful.
Zen the eff out of it!

![screen shot 2019-01-28 at 17 56 12](https://user-images.githubusercontent.com/962273/51904609-fac8e280-23b6-11e9-81c0-b6544e86b955.png)

**Comment by nylen** [comment]
@PointandStare I looked at the current screen, and there are 4 elements that link to the current user's profile (highlighted in blue boxes):

<img src="https://user-images.githubusercontent.com/227022/52230025-5c3ff400-2884-11e9-8e82-72d858571d8e.png" width="300">

This is maybe a bit excessive, and it definitely could use some improvement.  However, the existing behavior does seem to meet your "Expected behavior":

> Fast link to My Profile information.

As far as the new links you've suggested:

> - Change avatar (if possible)
> - Change password

What specifically would these link to?

Currently you click any of the 4 (!!) "My Profile" links to perform both of these functions via the profile page.

Changing the avatar requires you to read the instructional text and go over to Gravatar, and changing your password requires you to use form elements as part of a multi-step process.  Both of these steps are best done in the context of the full user profile page, though we may be able to improve the avatar selection flow when we [say goodbye to Gravatar](https://petitions.classicpress.net/posts/8/disable-gr-avatar-by-default).

So I think we could add these 2 new links to scroll & highlight to the appropriate section of the user profile page, but honestly I don't think that's a big improvement.  What else could we do with this section?

**Comment by PointandStare** [comment]
If we roll back a bit and ask 'why?' - why is this section here - it used to say 'Howdy' etc and then the links to 'my profile'.

If we look at what is the _need_ for this section, as it stands, I'm not sure - never did really understand as there are other on page options for doing the same thing, as you pointed out.

As far as I can see, referencing my logged in username/ profile directly and having a 'log out' function is possibly all it really needs.

**Comment by nylen** [comment]
> As far as I can see, referencing my logged in username/ profile directly and having a 'log out' function is possibly all it really needs.

There's a bit of repetition, but this is exactly what it does today.

**Comment by PointandStare** [comment]
That's my point - 3 links that do the same thing is simply silly.
BUT - If this is to be changed, should it simply be deleted or can it be put use to something better.

**Comment by bahiirwa** [comment]
I would suggest these changes.

- Edit my Profile (Since DP is embedded inset.)
- Change password (This is always a needed feature when user is sent new account not withstanding the change password email in their emailbox)
- Log out

**Comment by joyously** [comment]
This follows the admin trend of having the top-level link repeated in the dropdown (the first entry of the dropdown may be a different Label, but the same destination). By removing the Howdy, now the Labels are the same.
Please check if there is different information shown in multisite (for superadmin or not). And is it the same in the front end admin bar?
I don't think the Password link needs to be called out, as that is part of Edit Profile.
