### ISSUE TITLE
"Update now" link for theme is broken when JS disabled

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#384]
With JS disabled, you can click these links and nothing appears to happen.

![2019-02-26t22 29 41-05 00](https://user-images.githubusercontent.com/227022/53463846-1eaf3080-3a16-11e9-9a25-e7cdbc911750.png)

The same bug should apply to WordPress, since we haven't changed this code.

**Comment by KTS915** [comment]
Closing this because we've now got a directory of ClassicPress themes and should focus on that. If WP decides to address this, we can adopt their fix if desired.

It's also worth noting that, despite appearances, this is not actually a link. It's a button, styled to look like a link. This might mean it's not misleading to screenreaders. If that's true, there's much less reason to be concerned about this anyway.
