### ISSUE TITLE
Improving the docs for contributions.

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#423]
While reading the forum, I found out that we have some rules to contributions especially for backports. I have seen @nylen also highlight this over two times in this comments on PRs.

Can we add this https://classicpress.slack.com/files/UCFQJPU4Q/FFV8NM0TZ/How_to_backport_a_WordPress_changeset to our docs to enable smooth contributions. 

Is this workable? We seem to replicate it everytime in comments. Docs would be a reference solution.

**Comment by nylen** [comment]
Another thing to add to contribution guidelines regarding **bugfixes**, from #419:

> > Generally when evaluating bugfix PRs I look for these things (ideally all of them)
> > 
> > * The change impacts existing ClassicPress users. (Otherwise, there are literally thousands of things we could look at, but we need to prioritize our development time.)
> > * The change is not going to break any other use cases.
> > * The change has automated tests.
> > * I understand the change very well, or I can ask questions of someone who understands it very well.
> 
> Could we adopt this in the contributions section of the read me? It might iron out some issues for PRs

I'm not sure the best way to organize this information though - could be in our CONTRIBUTING.md file, which is already linked from the main readme.

**Comment by bahiirwa** [comment]
Shouldn’t that be somewhere in contributions section in readme.md? It’s information to consider before even taking time in creating a PR.

**Comment by ginsterbusch** [comment]
Hm .. readme might get too crowded for this. Maybe use the Github wiki for temporary documentation, point to it from the Readme, within a rather generic outlined "how to contribute" section?

cu, w0lf

**Comment by bahiirwa** [comment]
I have tried something like that here in my branch. Could this suffice? https://github.com/bahiirwa/ClassicPress/tree/docs

**Comment by nylen** [comment]
CONTRIBUTING.md is the standard place on GitHub for this information. The GitHub UI shows links to this file in several places if it is present.

I'd also prefer this over the GitHub wiki because that way all the contributing information stays in one page. Also, we already have docs.classicpress.net and www.classicpress.net/faqs, and the wiki would be just one more thing to maintain and update.

Don't forget too about the [issue template and pull request template](https://github.com/ClassicPress/ClassicPress/tree/develop/.github) which already exist.

**Comment by bahiirwa** [comment]
PR submitted https://github.com/ClassicPress/ClassicPress/pull/428

**Comment by bahiirwa** [comment]
Note: I realized we have something very limited on the CP website about conduct and this is only in the forums. 

Pinging @KTS915 to advise.

**Comment by KTS915** [comment]
@bahiirwa Where else are you thinking that there should be some sort of code of conduct? Are you thinking of the new plugins directory? If so, I'd say it's a bit hard to draft that yet when we haven't worked the technical details of how that will work. But perhaps you're thinking of somewhere else?

**Comment by bahiirwa** [comment]
You make a valid point. I haven’t thought about anything outside this repo and forums. Do you think the little note I added to the PR makes sense? Does it suffice?

**Comment by KTS915** [comment]
@bahiirwa With one exception, it looks pretty good to me. I always like to start such things at a general level because they are more likely to cover everything, including stuff that isn't foreseen. Adding stuff that is more specific is always problematic, because that tends to imply that other things aren't covered. So it's really only worth doing if we experience a real need to do so.

On that basis, I'd remove the reference to "body size." It's already covered by personal appearance, and including it creates a whole bunch of questions. What about hair color, for example, or having lots of/no hair? Just leave that phrase out and keep everything more general.

**Comment by nylen** [comment]
The initial version of the contributing guidelines here is merged. The code of conduct bits are handled by linking to our existing code of conduct: https://www.classicpress.net/democracy/#democracy-conduct
