### ISSUE TITLE
Missing rewrite rule on fresh installation

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#430]
After installing, clicking to view the Uncategorized category archive produces a 404 error.

## Expected behavior
Archive is displayed; no 404.

## Current behavior
404 error

## Possible solution
Flush the rewrite rules as a final operation of installation.

## Steps to reproduce (for bugs)
1. Install ClassicPress
2. Visit: `Dashboard` > `Posts` > `Categories`
3. Hover the _Uncategorized_ category item and click to `View`
4. Error 404

**Comment by johnalarcon** [comment]
Confirming that this behavior exists in WP 4.9.10.

**Comment by nylen** [comment]
Slack discussion: https://classicpress.slack.com/archives/CCNEEH86P/p1561755866061200

I believe this is an issue local to @johnalarcon's current server setup, because I was not able to see it locally on a fresh install.  I am also fairly certain this would have been reported against WordPress already, but https://www.google.com/search?hl=en&q=site%3Acore.trac.wordpress.org%20uncategorized%20rewrite does not appear to yield any relevant results.

**Comment by johnalarcon** [comment]
Yeah, it's something with my local server. The behavior did not occur under CP or WP (4.9.10) on a live server.

**Comment by nylen** [comment]
You might want to check the content of `.htaccess` immediately after installation, and then again once you visit the permalinks page.

Closing this, I would suggest a thread on the [support forum](https://forums.classicpress.net/c/support/version-1) with a link back to this issue if you are still having trouble here.

**Comment by johnalarcon** [comment]
I traced it back to the source. I was preserving my htaccess rules (tons of 'em) across installs. ClassicPress had tacked on it's rules at the end and I just didn't notice as it was hundreds of lines down the file. So, the fresh install was obeying the wrong rules. Mystery solved. Thanks for putting up with me. :D
