### ISSUE TITLE
Targeting companies using REST API

### ISSUE THREAD

**Issue by szepeviktor** [ClassicPress/ClassicPress#437]
We could bootstrap CP in a way that allows the REST API to answer **several** requests.

Something like https://github.com/php-pm/php-pm

Now 100 REST API requests result in CP starting 100 times.
What do you think?

**Comment by ginsterbusch** [comment]
Which means, for a regular install with approx 100 MB memory usage, 100 x 100 MB = 9,78 GB memory usage? :wink: 

cu, w0lf.

**Comment by szepeviktor** [comment]
It need a custom bootstrap that loads initially and stays in memory.
That all HTTP requests will be routed through the **modern** REST API classes.
Done!

**Comment by nylen** [comment]
I think this would mostly need to be done at the server level.

Does ClassicPress need code changes to support this use case? If so, what might that look like?

**Comment by szepeviktor** [comment]
Currently ClassicPress boots up, runs and shuts down. That may be [very slow](https://medium.com/@yairlevy/wp-rest-api-too-slow-2da859f3cc93).

What I am talking about is boot up in special way then server REST API request several times -> sparing the boot-up time, basically immediate execution.
I think it is only possible for REST API as
- we need no Rewrite API
- we need no template files
- REST API classes are clean and modern

What do you think about it?

**Comment by szepeviktor** [comment]
@dnna Gave a detailed answer over at php-fm https://github.com/php-pm/php-pm/issues/458#issuecomment-508229102
Now we should not think anymore but type!

**Comment by Mte90** [comment]
We should remember that Rest api include their Rewrite API custom system and they don't load the language files not needed (this in wp 5.0, I am not sure if we backported that).
Maybe we need to start with a feature plugin and later see how to integrate it, so we don't need to focus a lot about the CP side.

**Comment by szepeviktor** [comment]
As this would be a **process manager** it could not run with the existing PHP setup.

It needs a reverse proxy (e.g. mod_proxy_http) to connect to the web as php-fm does not do SSL termination and is not a general purpose web server.

**Comment by Mte90** [comment]
Ok so require a change from php side and web server side, maybe also for apache and not only nginx.

**Comment by nylen** [comment]
What needs to be done here at the code level is still not very clear to me.  Feel free to provide a proof-of-concept, but I agree a plugin would be a better starting point for this.

**Comment by nylen** [comment]
Actually I have seen something like this before: https://github.com/Automattic/prefork

The approach it uses is a bit different - pre-initialize PHP processes and fork them as needed when requests come in.

>There is an important limitation on what can be done in a prefork app loader. Generally, don't rely on any conditions or values set by the request; you may only rely on conditions and values that are constant across all requests.

This is not an easy requirement to satisfy with large teams and/or complex applications! As the readme indicates, Automattic dropped this approach when they adopted PHP 7.

Approaching this problem as described in the original issue (having a single process manage multiple API requests) is also likely to cause issues with many setups, because there are lots of parts of WordPress/ClassicPress and plugins that are not designed to be re-used multiple times in the same request.  A couple examples are global objects which are only initialized when needed, and also any `static` variables inside functions.

Personally I would go for an application-specific cache here instead. The logic to make this work correctly for the REST API and all its possible endpoints, query parameters etc. is not trivial either.

**Comment by viktorix** [comment]
@nickchomey This was before my time, and everyone on this issue is no longer contributing to CP. This appears to be only a discussion. 

Is there anything specific you're looking for? any requirements? The more information we have about use cases, the easier it is to see if it's something that more users might need and something we can look into implementing.

**Comment by KTS915** [comment]
Wouldn't an object cache be the way to go?

**Comment by KTS915** [comment]
I know the difference between the two, but that's a matter of method. What is your objective? To speed things up and make them scale. In CP (and WP) that's best done by object caching.

If you really want to use the specific approach you appear to favor, then (as the docs to which you allude themselves make clear) CP/WP isn't for you.
