### ISSUE TITLE
Potential issues with release packages (formatting, etc)

### ISSUE THREAD

**Issue by jessuppi** [ClassicPress/ClassicPress#453]
Great to see ClassicPress continuing to evolve! After testing your packages for the last few weeks with our [SlickStack](https://github.com/littlebizzy/slickstack) installation script, a few suggestions:

**1. Repos.** Is there a critical reason why your releases require a different repo?

https://github.com/ClassicPress/ClassicPress-release/releases/

**2. Naming.** Is it possible to move toward a more standard naming scheme for easier package distribution and to avoid general confusion? For example, something like:

- classicpress.zip (latest/default)
- classicpress-1.0.1.zip
- classicpress-1.0.2.zip

...inside the classicpress-1.0.1.zip a user might expect a folder `classicpress-1.0.1` ... currently the archives and folders are a bit hard to understand.

**3. Formatting.** After a few weeks of testing across Linux and Chromebook, we kept having issues when moving your packages around, renaming, uploading, unzipping, etc. In some cases this resulted in empty archives, and other issues. There might be more than one cause, but primarily it seems to be caused by line ending conflicts in Git:

https://help.github.com/en/articles/configuring-git-to-handle-line-endings
https://gist.github.com/shiftkey/b51f29301e52a3bc74d9

This often happens when various team members are working with multiple environments. This issue could be mitigated in several different ways, but ultimately if packages are tested and then hosted on a file server for public download, it might matter less, because third parties would not have to be accomplishing some of those steps.

**4. Hosting.** This leads to file hosting, if possible re-hosting the packages on a server that already has sorted out the naming and permissions issues would be awesome, it would also probably engage less tech-savvy users who want to try out ClassicPress. Cheers!

**Comment by nylen** [comment]
Hi @jessuppi, answers to these questions below -

>1. Repos. Is there a critical reason why your releases require a different repo?

Yes. This is the same setup as WordPress where there is a development repo (source code before build process) and a release repo (files after build process).

We also use GitHub to build our release zip files from signed `git` tags. Most of the time you don't need to worry about this, but it will be a key part of our update signature verification later on.

>2. Naming. Is it possible to move toward a more standard naming scheme for easier package distribution and to avoid general confusion?

This is already done:

- https://github.com/ClassicPress/ClassicPress-release/archive/1.0.1.zip
- https://github.com/ClassicPress/ClassicPress-release/archive/1.0.0.zip
etc.

When you download these files in a browser or using `wget --content-disposition` they will be saved as e.g. `ClassicPress-release-1.0.1.zip`. This zip file contains a folder named `ClassicPress-release-1.0.1` with all the ClassicPress files inside it.

As part of our upcoming site redesign, we plan to provide a download page that links directly to these files on GitHub instead of requiring users to find the right links.

>3. Formatting. After a few weeks of testing across Linux and Chromebook, we kept having issues when moving your packages around, renaming, uploading, unzipping, etc. In some cases this resulted in empty archives, and other issues. There might be more than one cause, but primarily it seems to be caused by line ending conflicts in Git:

Generally you will see the same patterns of line endings etc. between WordPress and ClassicPress. The most likely explanation here is mistakes made when handling files/archives. We'd be happy to look into more specific cases, but this is the first we've heard or seen of such issues.

Using the correct release downloads from GitHub should also avoid basically all of this.

>4. Hosting. This leads to file hosting, if possible re-hosting the packages on a server that already has sorted out the naming and permissions issues would be awesome, it would also probably engage less tech-savvy users who want to try out ClassicPress. Cheers!

Naming has been covered above, and the mention of "permissions issues" is something new but again not something we've seen before. Please be more specific regarding any permissions issues you've had and we can look into it.

Releases will continue to be hosted on GitHub, because this saves us bandwidth and also improves our security profile. However I think linking directly to the correct release zipfile will address this concern, as less tech-savvy users will no longer have to browse through GitHub to get the correct download.

**Comment by jessuppi** [comment]
Repos aside, and not trying to get too philosophical here, but in the interest of emulating WordPress releases as much as possible for usability reasons etc, compare below:

https://wordpress.org/wordpress-5.2.2.zip

...produces a folder: `wordpress` ... I think in some places its `wordpress-5.2.2`

This would allow, for example, a standard script like:

    wget classicpress.zip (or) wget classicpress-VER.zip
    unzip classicpress*.zip

So the release naming is definitely a big issue in terms of standardization and usability, esp. for a fork of WordPress that is trying to attract the same userbase.

`lowercasename-VER` is pretty standard these days for [most packages](https://packages.ubuntu.com/bionic/allpackages).

> Generally you will see the same patterns of line endings etc. between WordPress and ClassicPress. The most likely explanation here is mistakes made when handling files/archives. We'd be happy to look into more specific cases, but this is the first we've heard or seen of such issues.

Except its not, try uploading zips of ClassicPress to GitHub for example, even GitHub.com will issue a line ending warning message in many cases. =\

> Releases will continue to be hosted on GitHub, because this saves us bandwidth and also improves our security profile. However I think linking directly to the correct release zipfile will address this concern, as less tech-savvy users will no longer have to browse through GitHub to get the correct download.

Using [GitHub Pages](https://pages.github.com/), we re-host lots of packages for free.

Speaking as the author of the first deployment tool to support ClassicPress, I'd suggest the team here more thoughtfully consider my feedback. There's a careful balance between trying to modernize ClassicPress and respecting the usability that makes WordPress popular. Cheers!

**Comment by nylen** [comment]
This will work at the moment:

```
wget https://github.com/ClassicPress/ClassicPress-release/archive/1.0.1.zip -O classicpress-latest.zip
unzip classicpress-latest.zip
# release files are now in ./ClassicPress-release-1.0.1/
# note, this assumes there is only one ClassicPress-release-* directory or file present
mv ClassicPress-release-* classicpress-latest
```

As a future improvement, we can also add something like `https://www.classicpress.net/classicpress-latest.zip` which would be a redirect to the correct package. This would come as part of our upcoming site redesign which includes code to list ClassicPress releases.

>try uploading zips of ClassicPress to GitHub for example, even GitHub.com will issue a line ending warning message in many cases. =\

Thanks for including this detail about how and where you run into line ending issues.

Whenever you add a binary file to a `git` repository you should mark it as binary to avoid line conversion attempts ([more info](https://stackoverflow.com/questions/7994811/git-mark-file-as-binary-to-avoid-line-separator-conversion)).

I'm not sure why you're only running into this issue with ClassicPress, but if you take a look at any sufficiently large zip file (WordPress, ClassicPress, or anything else) using a hex editor then you will find numerous instances of `\r\n` (`0x0d 0x0a`) and any other sequence of line ending characters that you might want to look for. These sequences will be randomly distributed throughout the zip file because it is compressed binary data.

Handling binary data correctly is a `git` usage detail, not an issue with the way ClassicPress is packaged.

>if packages are tested and then hosted on a file server for public download, it might matter less, because third parties would not have to be accomplishing some of those steps.

The correct download URLs to use are listed in my replies. These packages are indeed "tested and then hosted on a file server for public download".

>Speaking as the author of the first deployment tool to support ClassicPress, I'd suggest the team here more thoughtfully consider my feedback.

Thanks for creating this issue, and we are considering your feedback.  The same as when reporting any technical issue, it helps to provide exact steps that demonstrate specific issues.

**Comment by nylen** [comment]
> As a future improvement, we can also add something like `https://www.classicpress.net/classicpress-latest.zip` which would be a redirect to the correct package.

I've moved this over to https://github.com/ClassicPress/ClassicPress-Network/issues/52, closing this one.
