### ISSUE TITLE
password reset email link faulty in some email clients

### ISSUE THREAD

**Issue by mattyrob** [ClassicPress/ClassicPress#467]
As per Slack discussion and existing WP ticket (https://core.trac.wordpress.org/ticket/44589) We need to consider aback porting at the fix or creating our own.

## Expected behavior
Reset links should work in all email clients

## Current behavior
A trailing '>' in the links corrupts the link in some email clients resulting in failing behaviour when resetting passwords is attempted.

## Possible solution
Remove the angle brackets from around the link, they were introduced for wrapping years ago but that should no longer be a concern.

## Steps to reproduce (for bugs)
1. Ensure you are logged out
2. Visit wp-login.php and follow the links for forgotten password
3. View the resulting email in an affected email client to see the '>' character appended as part of the link, and thus breaking the  links expected behaviour
4.

## Context
Can affect all site with members that are trying to reset their passwords.

**Comment by Mte90** [comment]
As I can see the patch in wordpress is not moving on because needs unit tests, so we need unit tests too :-)

**Comment by mattyrob** [comment]
The function we need to test, `retrieve_password` is located in the wp-login.php file. That isn't included in WordPress by default so the function isn't available to test.

Including wp-login.php in a unit test causes header information to be sent again and the test errors - any tips on a workaround for that would be appreciated.

**Comment by Mte90** [comment]
You are right seems that the whole file doesn't have any unit test, so this is something that we need to do in ClassicPress.

**Comment by nylen** [comment]
I can only assume the "needs unit test" flag was added to that ticket due to the alternative approach which was discussed there, i.e. "make the secret key ignore the closing bracket when it is sent".

I like automated tests as much as anyone, but we can make a 1-line change in an email without requiring tests for all of wp-login.php.

**Comment by mattyrob** [comment]
@nylen Thanks for the commit. As an aside I figure out how to unit test the wp-login.php file so it can be done if you want a PR for that. We could also consider testing more that the password reset email link too if there are other parts of the code worth automating tests for.

**Comment by nylen** [comment]
@mattyrob Sure, I am certainly not going to turn down PRs that add tests.

**Comment by mattyrob** [comment]
@nylen How does this look before I create a PR:
https://github.com/mattyrob/ClassicPress/commit/4bf8e65f01c21954fe0a877b0284ce9e90bb234d

**Comment by nylen** [comment]
That looks nice and clean, I was expecting that task to be a good bit more difficult actually!

A few comments:

- Double-check the indentation, all lines should be using tabs at the beginning, and `/*` style comment blocks should have one space before the `*` in the middle of the block:

```
[tab][tab]/*
[tab][tab] * note space before asterisk, and on the next line
[tab][tab] */
```

- How about matching the whole line instead of using `[^<]` and `[^>]` in the regex?

- Obscure, but it's possible to change the test domain from `example.org` by setting the `WP_TESTS_DOMAIN` constant. It should be fine to use `[^/]+` instead of the domain.

**Comment by mattyrob** [comment]
A change was made upstream to another file, Ive created a new PR.
