### ISSUE TITLE
Modify / remove WordPress logos

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress#5]
In /wp-admin/images and /wp-includes/images

Logo files attached:

[classicpress-logo.zip](https://github.com/ClassicPress/ClassicPress/files/2332667/classicpress-logo.zip)

**Comment by marctenax** [comment]
Fantastic!

**Comment by scottybo** [comment]
Let me know if you need any other formats @frozzare :)

**Comment by frozzare** [comment]
@scottybo I need some svg formats since there are two svg logos:
/wp-admin/images/wordpress-logo.svg
/wp-admin/images/wordpress-logo-white.svg

all others logos I could find in /wp-admin/images and /wp-includes/images is replaced in my fork right now https://github.com/frozzare/ClassicPress/tree/issue/5

**Comment by scottybo** [comment]
Will get those prepared ASAP, likely to be tomorrow now

**Comment by scottybo** [comment]
SVGs attached (as zip, github doesn't support the in their vanilla format)
[svg-icons.zip](https://github.com/ClassicPress/ClassicPress/files/2339967/svg-icons.zip)


Agreed - the rename can happen as part of #3
