### ISSUE TITLE
Changelog entries missing from about.php

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#515]
The about.php page (after update or install) is missing some changelog entries.

## Expected behavior
Changelog reflects all releases.

## Current behavior
Only the changelog for 1.0.0 is listed.

## Possible solution
Add the newer releases to the changelog.

## Screenshot
![image](https://user-images.githubusercontent.com/12477319/67811633-76e17b00-fa5a-11e9-878d-0ae5583cdba5.png)

**Comment by nylen** [comment]
This is somewhat intentional, but there is definitely room for improvement in how this looks today.

We already have 2 places where the changelog needs to be compiled, and I'd very much like to avoid a 3rd one, especially if we wouldn't be able to update these entries without doing a new release.

I've been thinking about a couple of alternatives. One is #512 which is an intermediate step that makes it a bit clearer what is going on there, and #449 would be a more complete solution.

**Comment by nylen** [comment]
Here's how this looks today:

![2020-02-18T18-40-27Z](https://user-images.githubusercontent.com/227022/74767121-26e32a00-527e-11ea-87fb-cd8d560072a2.png)

In order to add links to the missing entries, we could add an API call/endpoint that knows how to fetch a list of all the forum threads in the Release Announcements category. Otherwise the next step to improve the changelog display would be as described in #422.

**Comment by viktorix** [comment]
v2.0 will include an updated About page.
