### ISSUE TITLE
Fields

### ISSUE THREAD

**Issue by szepeviktor** [ClassicPress/ClassicPress#518]
If ClassicPress is really going to be a CMS it needs to have simple **custom fields** and **custom views** (see Drupal).

Fields API was a feature project 2 years ago: https://github.com/sc0ttkclark/wordpress-fields-api

**Comment by nylen** [comment]
Hi @szepeviktor, personally I agree with you, but since this would be a major change, our petitions site is a better starting point.

There is already a petition for this: https://petitions.classicpress.net/posts/76/finish-the-custom-fields-api

We have a way to try some features as experimental "research plugins", which has already been started at https://github.com/ClassicPress-research/custom-fields

I see that you have already commented and voted on the petition, so if you are interested in helping out with the development of this plugin then I would contact the people who started that research plugin (@mikeschinkel and @gschoppe) and discuss similarities/differences from the `wordpress-fields-api` project you mentioned, next steps, etc.

**Comment by KTS915** [comment]
Closing as there's been no movement on this, and it's too vague anyway to be actionable.
