### ISSUE TITLE
Encryption in CP/WP

### ISSUE THREAD

**Issue by ray-ang** [ClassicPress/ClassicPress#523]
The GDPR and privacy laws state that personal data need to be encrypted at rest and in transit. As such, using CPT and postmeta to hold personal info means the need for application layer encryption.

Is it a good idea to add encryption and decryption functions in CP core, like wp_encrypt and wp_decrypt?

Thanks.

**Comment by ginsterbusch** [comment]
That is news to me. Which privacy laws of which country? 

FYI: The GDPR is a set of rules for the European Union, which each country that belongs to the EU has to implement in their own way. Also, strictly speaking, the GDPR does not explicitely state personal data has to be encrypted, but strongly suggests it as a common measure. 

There are quite a few articles going into depth about the topic, but this one here is one of the better understandable ones I've could dig up: https://www.i-scoop.eu/gdpr-encryption/

So, in theory, the "in transit" part you are referring to probably means "during data transfer", ie. from the client to the server, and vice-versa. This is were TLS aka SSL comes in, and why there are so many warning messages in almost all up-to-date CMSes, including WP, when you do not use SSL for the frontend side of your CMS.

How would one make sure that data is de- and encrypted in the database is something entirely different though. My personal guess is, that this should be implemented using a plugin or a set of plugins, because actual encryption needs CPU power, which a typical shared hosting environment hasn't much to spare.

There is also the question what user data is being stored, based on what use case. In a regular CMS scenario, the only data being stored typically are one or several backend / admin interface logins, so, at most, an e-mail address, a login name and the password hash. On the frontend facing side, there would only be cookie storage, which happens entirely on the client side. When using a strongly reduced theme like Susty, there won't be even that.
Some sites include a contact form, but most of these do not store data in the database, instead sending out the data directly via mail. Aside of that, on GPDR-compliant sites, you normally would have to accept the processing of the data you sent to the site owner using the contact form, which is usually implemented using an Opt-In acknowledgement (eg. a checkbox and a link to their data handling TOS, with a short form for the actual acknowledgement text).

A different use case would be an e-commerce site, with a shopping cart and an order process, eg. using WooCommerce, or even something as simple as a request / contact form, for making inquiries about availablity and pricing of a specific product. Hence the plugin territory - as you cannot simply assume everyone is using an identical setup, whether it'd be your bog standard shared hosting environment, some intermediate, more sophisticated semi-shared hosting or (managed) VPS environment, or a superbly configured, custom built, self-managed server cluster with a system administrator always hovering around to ensure it performs near-perfect.

cu, w0lf.

**Comment by ray-ang** [comment]
I agree data encryption in transit can be addressed by SSL/HTTPS. The concern is more on data at rest in the database.

Data encryption at the application level can easily be done using libraries like openssl or libsodium, and do not need a greater amount of CPU power. These ease and availability of free libraries would imply security measures to enforce encryption should be done. Otherwise, this could be an aggravating circumstance in case of a breach.

With regards to the use of plugins for encryption, due to the free and open source nature of plugins, using plugins may actually involve security code review since plugins are third party codes. So it may be a better choice to implement encryption without plugins. In general, the lesser third party plugins, the better in terms of security and code review.

**Comment by ginsterbusch** [comment]
My suggestion for you would be to [create a petition](https://petitions.classicpress.net/) for this specific topic, as it looks very much to be a breaking change, if implemented directly into CP core.

cu, w0lf.

**Comment by nylen** [comment]
My understanding is also that GDPR does not specifically require data to be encrypted at-rest, just that "reasonable security measures" be taken.

For anything short of credit card numbers, bank accounts, medical records etc, I'd argue for other measures like limiting access to a site's database via a firewall and setting the server permissions so that the application cannot overwrite its own files. These are less invasive but still very effective (in some cases even more so).

There are also a lot of questions to solve around implementation: what algorithm should these encryption functions use? What key should they use? What happens to old data when the encryption key needs to change?

These aren't trivial problems to solve, and the right answer probably depends to some extent on the specific application. So for now you will probably want to use libsodium for the critical parts of your application, and I agree it would be a good idea to start a petition to gauge interest in this feature.

**Comment by ray-ang** [comment]
I will prepare a petition for encryption functions. Probably two functions - wp_encrypt and wp_decrypt - in the formatting.php file. They will just be available if the user needs to use them, but they won't be invasive as to affect get_metadata or update_metadata functions since most metadata would not need encryption.

**Comment by ray-ang** [comment]
I added a petition re: encryption functions ( https://petitions.classicpress.net/posts/193/add-encryption-functions-to-core ). The goal being is that since CP is a business-focused CMS and can be used as application development platform, the availability of such encryption functions would aid developers in encrypting necessary personal data using built-in functions.

**Comment by ray-ang** [comment]
I apologize but I have to vote against my own proposal for encryption mechanisms within CP, core or core plugin. Encryption should not be made available to those who do not know programming or databases. If encryption is done with PHP, the developer should know PHP and should be able to check the database if data was indeed encrypted. E-commerce, e-learning or membership sites who need to encrypt data such as email, fullname, phone or address should approach this using codes and proper knowledge of encryption.
