### ISSUE TITLE
Elementor 2.8.x Not Compatible

### ISSUE THREAD

**Issue by yaffeweb** [ClassicPress/ClassicPress#530]
Elementor and Elementor Pro 2.8.x require Wordpress 5.0+

## Expected behavior
Updating the plugin should add new features

## Current behavior
Plugins deactivate and break site because of unmet compatibility circumstances
## Possible solution
At this point, the only solution would be to move to 5.0 base code
## Steps to reproduce (for bugs)

1. Install Classicpress
2. Install version 2.7.x of Elementor
3. Update Plugin to latest version
4. Watch it deactivate and break your site.

## Context
I'm just trying to update to latest versions of available plugins. Everything has worked great so far until elementor 2.8.x. I don't necessarily blame either classicpress or elementor, I just wish that both would get on the same page so I can use the latest features of both. Right now, I have to use the 2.7 of Elementor because the newest version isn't compatible.

**Comment by ginsterbusch** [comment]
>  Watch it deactivate and break your site.

It actually does not deactivate. Its just "not running":

![Elementor 2.8.2 error message](https://gfx.fwolf.de/images/2019/12/23/Auswahl_228.png)

**Comment by ginsterbusch** [comment]
Sadly, a try on doing a quick fix by changing the required WP version number down to 4.9 inside elementor.php did not really help - Elementor will run, per se, but when trying to create a new page, the component sidebar is loading into oblivion. There also is an error message shown in the JS Console, source being editor.min.js of Elementor. My guess is that the developers started to re-use components from within Gutenborg, and not supplying them themselves anymore.

cu, w0lf.

**Comment by nylen** [comment]
Yes, Elementor 2.8 is no longer compatible with WP 4.9 (and by extension ClassicPress). This appears to be because they reference the block editor / Gutenberg components in their code, regardless of whether you're using it or not.

> move [ClassicPress] to 5.0 base code

This has come up several times but it is not a direction for ClassicPress in the foreseeable future. It would mean many major changes and it would make our maintenance and releases many times more difficult. For just one reason why, we'd basically be including all block editor code for plugins to use if needed, but leaving it disabled, which is a different configuration than what WP is doing and therefore very likely to introduce more problems and incompatibilities.

Of course anyone is welcome to explore this approach in their own fork or branch, but I'd expect it to be a huge amount of effort to get it working reasonably well first, and then to update it for future versions of WP as more incompatibilities appear.

> Right now, I have to use the 2.7 of Elementor because the newest version isn't compatible.

This is correct. It's worth reaching out to Elementor directly if you'd like them to restore support for WP 4.9 and ClassicPress.

There is also some more relevant discussion in our forums:

- https://forums.classicpress.net/t/good-bye-elementor/1782/12
- https://forums.classicpress.net/search?q=elementor%20order%3Alatest

I'm closing this issue as there is nothing for ClassicPress to do here.
