### ISSUE TITLE
Missing rel="noopener noreferrer" to any target="_blank"

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#537]
I submitted #532 to WP to make some comparison notes and realized they have another implementation going on i.e. https://core.trac.wordpress.org/ticket/37941.

As I feared there are more files with this issue and the patches pick it out. How do we proceed with this? Do we make minor patches to CP because this has lagged with WP for over 2-3 years.

**Comment by nylen** [comment]
There are a lot of WP changesets to backport in order to adopt this feature fully. Here are just a couple more:

- https://core.trac.wordpress.org/changeset/42770
- https://core.trac.wordpress.org/changeset/46894

These are related to adding the `rel` attribute to links entered in the editor, comments, etc. We probably want to at least split the patches between these "user-generated content" changes and the admin interface changes, like what you started in #542.

Also related: #560 since this change depends on the same code being in place.

**Comment by viktorix** [comment]
Will be included in v2.0.
