### ISSUE TITLE
Introduce lazy-loading API for media and other elements

### ISSUE THREAD

**Issue by joyously** [ClassicPress/ClassicPress#538]
As the browsers evolve to handle the `loading="lazy"` attribute, core can use the attributes for images to enhance sites for those with browsers that handle it. And it will be ignored by other browsers. And by not adding the attribute when it already exists, users can use other solutions as well.

See full write-up: https://make.wordpress.org/core/2020/01/29/lazy-loading-images-in-wordpress-core/

The feature is coded in a WP feature plugin: https://github.com/WordPress/wp-lazy-loading
It is scheduled to be added to WP 5.4, see https://core.trac.wordpress.org/ticket/44427

**Comment by nylen** [comment]
Thanks, this is a good one to watch what WP does.

**Comment by viktorix** [comment]
Would be nice to add lazy loading finally to CP. There are multiple changesets for this, am I missing any?

https://core.trac.wordpress.org/changeset/48272
https://core.trac.wordpress.org/changeset/48237
https://core.trac.wordpress.org/changeset/48170
https://core.trac.wordpress.org/changeset/47554

These 2 update the same docblock, due to an issue in the first changeset:
https://core.trac.wordpress.org/changeset/48648
https://core.trac.wordpress.org/changeset/48649

Lazy loading iframes weren't part of this. It's part of a different ticket. Should we combine everything?
https://core.trac.wordpress.org/ticket/50756

One changeset for this:
https://core.trac.wordpress.org/changeset/49808

**Comment by joyously** [comment]
There were some problems associated with lazy iframes. I don't remember the fix. Be sure to search carefully for that if you put it all into one. 
It looks like you listed all the changesets for that one ticket, although in reverse order for the first 4.

**Comment by joyously** [comment]
I agree that the iframes should be separate. It looks like changeset 50682 affects images also, since they decided that it shouldn't affect hidden images or iframes.
_50683 was just for package-lock.json, and 50684 was the same thing for a different branch._
It seems like there were a lot of support topics about missing images, but I'm not sure if the lazy load was a factor. A lot of people have trouble with SSL making images not show.

**Comment by mattyrob** [comment]
I have created a draft PR for the image changes to enable lazy loading - I found a missed changeset during the backport process.

There are performance enhancements in changeset:
https://core.trac.wordpress.org/changeset/52065

But these improvements impact lazy loading of images and iframes so perhaps we should consider landing this as a completed change for images and iframes and with the associated performance improvements.
