### ISSUE TITLE
Allow to define TEMPLATEPATH and STYLESHEETPATH  in wp-config.php or similar

### ISSUE THREAD

**Issue by yannux** [ClassicPress/ClassicPress#595]
Hello, 

( First issue, I hope it's well submitted. Sorry if my english isn't accurate ) 

I run ClassicPress integrated in [Roots.io bedrock](https://roots.io/bedrock/), so we have config file for different env (prod, staging, dev ).  
it would be practical to be able to define TEMPLATEPATH and STYLESHEETPATH in those files like we can already do with WP_DEFAULT_THEME

## Expected behavior
```
define('TEMPLATEPATH', WP_CONTENT_URL . '/themes/' . WP_DEFAULT_THEME);
define('STYLESHEETPATH', TEMPLATEPATH);
```

## Current behavior
You can't define those because function `wp_templating_constants()` don't check if already defined.

## Possible solution
Make same as WP_DEFAULT_THEME

```
function wp_templating_constants() {
	/**
	 * Filesystem path to the current active template directory
	 * @since WP-1.5.0
	 */
	if ( ! defined( 'TEMPLATEPATH') ) {
	        define( 'TEMPLATEPATH', get_template_directory() );
        }

	/**
	 * Filesystem path to the current active template stylesheet directory
	 * @since WP-2.1.0
	 */
	if ( ! defined( 'STYLESHEETPATH') ) {
        	define( 'STYLESHEETPATH', get_stylesheet_directory() );
       }

	/**
	 * Slug of the default theme for this installation.
	 * Used as the default theme when installing new sites.
	 * It will be used as the fallback if the current theme doesn't exist.
	 *
	 * @since WP-3.0.0
	 * @see WP_Theme::get_core_default_theme()
	 */
	if ( ! defined( 'WP_DEFAULT_THEME') ) {
		define( 'WP_DEFAULT_THEME', 'classicpress-twentyseventeen' );
	}

}
```

## Context
I'll make more easy to automatically switch theme for different env, calling less functions / filters, and maybe it's more consistent with the possibility of being able to define WP_DEFAULT_THEME

**Comment by nylen** [comment]
I haven't heard of this use case before. It seems harmless enough at the code level, but I wonder whether other parts of the system might still think that a different theme is active.

Normally the active theme is set by `get_option( 'template' )`. Are you actually using a completely different theme in dev/staging/prod, or something else? Can you explain a bit more about your setup and why you need to override `TEMPLATEPATH` and `STYLESHEETPATH` specifically?

**Comment by ginsterbusch** [comment]
@nylen after a few glances into the bedrock source code, my guess is that this system is constant-centric.
Hence, one would expect to be able to set stuff like TEMPLATEPATH etc. instead of using filter hooks.

@yannux A simple "workaround" for this would be something like `add_filter( 'option_template', array( 'my_class', 'fancy_filter_hook' ) )`, at the earliest possible point.

**Comment by yannux** [comment]
@nylen It is indeed a special case that led me to that, I had to remove one directory level on my project to make it more clean.

So `/data/web/xxxxx.tld/www/web/app/theme` become `/data/web/xxxxx.tld/web/app/theme`

I  need to deploy on multiple server (some for admin other for front) and I'm not allowed to put site on maintenance. 
So deploying on one server and updating wp_options record for template was not possible ( some server without the update will read new template option ... so wrong path for them.

Then I was searching how to set by code the template path and I get to something like @ginsterbusch proposed. 

But deeping into core files I saw `WP_DEFAULT_THEME` that we can define in config files ( wp-config.php or application.php for Bedrock like system ) and I was thinking that making `TEMPLATEPATH` and `STYLESHEETPATH` defineable in config file would be more easy and consistant with `WP_DEFAULT_THEME`, and more clean than using a hook

I think it's strange allowing to define WP_DEFAULT_THEME but not the two others... Maybe it's my brain :)

**Comment by nylen** [comment]
I took a closer look at the code and redefining these constants won't work as you are thinking:

https://github.com/ClassicPress/ClassicPress/blob/2f660154991ca29075ee814e448383f836eeb4dc/src/wp-includes/default-constants.php#L368-L373

Even if you could override the `TEMPLATEPATH` and `STYLESHEETPATH` constants, there is also **a lot** of code that calls `get_template_directory()` and `get_stylesheet_directory()` directly, and that code wouldn't be affected.

So, the most reliable way to do this is using filters, indeed I think it's the only possible way.

If you need to modify the *names* of the active parent and child themes then you can use the `pre_option_template` and `pre_option_stylesheet` filters. You may need to do that also, but since you're modifying the theme *paths* it looks like the right filters to use are `template_directory` and `stylesheet_directory`, which are inside of `get_template_directory` and `get_stylesheet_directory` respectively.

mu-plugins run earlier in the load order than these theme constants are defined:

https://github.com/ClassicPress/ClassicPress/blob/2f660154991ca29075ee814e448383f836eeb4dc/src/wp-settings.php#L259-L262

https://github.com/ClassicPress/ClassicPress/blob/2f660154991ca29075ee814e448383f836eeb4dc/src/wp-settings.php#L395-L396

This means you can add your filters in a mu-plugin and change the return values based on the site's environment (which you probably already have defined in `wp-config.php`). After doing this you should see (using `wp shell` or similar) that `TEMPLATEPATH`, `get_template_directory()`, `STYLESHEETPATH` and `get_stylesheet_directory()` all return your desired result.

There isn't really any other way to do this, and the introducing inconsistencies in the value of `TEMPLATEPATH` vs the return value of `get_template_directory` is not a good idea so I'm going to close this now.

> I had to remove one directory level on my project to make it more clean.

I'm thinking it's probably more clean not to modify the path structure that Bedrock wants to use, but the above approach should work anyway.
