### ISSUE TITLE
Fix Coding standards sniff and Failed tests

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#692]
Following https://github.com/ClassicPress/ClassicPress/pull/683#issuecomment-810873847 

Currently, we are allowed failing tests in the PHP Coding Standards and PHP Compatibility sniff tests. 

Could we dedicate a branch to fix those and then integrate it to the develop at a later stage? 

Would this be a wise move or should we fix individual failed CS sniffs on individual PRs? 

__Originally posted by @mattyrob in https://github.com/ClassicPress/ClassicPress/pull/683#issuecomment-810873847__

**Comment by joyously** [comment]
I thought that most of the PHP compatibility issues were fixed already, using the commits from WP.
I asked before about standards and got no answer, along with the question about a statement of which browsers are supported.
My personal opinion on the coding standards is that they are too strict with spacing. The parts about doc blocks really help with the parsing for the Code Reference, but CP is not currently aren't doing that, and if we did, there would be a crazy mixture of WP and CP version numbers.
WP had one massive ticket https://core.trac.wordpress.org/ticket/41057 that reformatted a lot of files, using a tool. (commit message of 'Code is poetry': https://core.trac.wordpress.org/changeset/42343 )

**Comment by nylen** [comment]
The 90 PHP compatibility issues are warning about some things that may or may not be a real issue, like usage of `func_get_args()` after function arguments have potentially been modified. It would be good to know what, if anything, WP has done about those. Other than that, we have accepted the WP changes that are definitely causing PHP compatibility issues.

Coding standards should be mostly the same as WP but we won't be able to accept their massive changeset. We will need to look at these individually. Probably the best way to do this is to start a long-running branch named something like `cleanup/coding-standards` then create small PRs that all merge into this branch. It would also be a good idea to look at and document what coding standards we really want to enforce. As an example, the checks for yoda conditions can be disabled, in favor of using `===` where possible (need to be careful with this in old code where we can't be sure of the data types involved).

Browser support is unrelated to this issue but is documented here: https://docs.classicpress.net/browser-support/

**Comment by bahiirwa** [comment]
@nylen the branch is a good idea. How can we implement 

- a local dev with precommits for the future PRs
- A local dev check WPCS. WooCommerce had this kind of check with node.

**Comment by nylen** [comment]
> a local dev with precommits for the future PRs

If you are asking about how to do the commits, you should do something like this:

- `git fetch upstream`
- `git checkout cleanup/coding-standards` - this is the base branch for all PRs related to coding standards
- `git checkout -b cs/my-standards-fix` - this is the branch name for your PR
- make your commits
- `git push origin cs/my-standards-fix`
- submit the PR as normal, but set the **base** branch to `cleanup/coding-standards`, like this:

![2021-04-17T20-00-52Z](https://user-images.githubusercontent.com/227022/115125481-d6697880-9fb7-11eb-997a-fd4c771e1925.png)

![2021-04-17T20-01-12Z](https://user-images.githubusercontent.com/227022/115125468-c0f44e80-9fb7-11eb-8aa3-6aea76ec407e.png)

![2021-04-17T20-01-29Z](https://user-images.githubusercontent.com/227022/115125488-e2553a80-9fb7-11eb-8451-25a78113692a.png)

---

> A local dev check WPCS. WooCommerce had this kind of check with node.

When you check out the repository, run `composer install`. This will install `phpcs`. You can see how `phpcs` is run during GitHub Actions here:

https://github.com/ClassicPress/ClassicPress/blob/3a758854b3433b4badb00fb6cbc8b5cc5c8a4874/.github/workflows/coding-standards.yml#L56-L62

Since these commands are [made available globally](https://github.com/ClassicPress/ClassicPress/blob/3a758854b3433b4badb00fb6cbc8b5cc5c8a4874/.github/workflows/coding-standards.yml#L51) you will need to prefix the executable name with `./vendor/bin/` to run them from the directory where `composer` installs them. You will probably also want to modify the options for `phpcs`. Try `./vendor/bin/phpcs --help` to get an idea of how this works, and here is an example command to check only one file:

```
./vendor/bin/phpcs -n -s src/wp-login.php
```

**Comment by viktorix** [comment]
This may have been completed in #958. Everything else will be included in v2.0.
