### ISSUE TITLE
Will the fork also address other issues?

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress#7]
Will this fork also address issues like below or will it "just" be WP 4.9.8 without Gutenberg?

* remove the Customizer
* remove REST API
* remove XML-RPC
* remove all pre-PHP 7 support
* remove hardcoded jQuery
* remove oEmbeds, emojis and all useless content filters
* remove old code, old functions, deprecated function support

(part of the list copied from [a comment on WP Tavern](https://wptavern.com/classicpress-gutenberg-not-included#comment-256952))

**Comment by scottybo** [comment]
Short answer: maybe. We're going to introduce a voting and debate mechanism into future decisions for ClassicPress. So if the masses want it, we will do it.

**Comment by senlin** [comment]
Okay, thanks for your answer. Any idea of a timeline for these things to get rolling?

**Comment by nylen** [comment]
We need to be careful to move slowly and sustainably.  The first priority needs to be getting a working, maintainable fork with a working release process and the possibility for future updates.

Beyond that, we also need to be extra careful about any changes that would break compatibility with existing themes and plugins, because then many people won't be able to switch to ClassicPress.  While there are some easy wins (PHP 5.2 :wave: :door:), most of the changes proposed in this issue would fall under that category.

So, at this point there is very little benefit in diverging from WP.  We are all here because we like WP and we think it is one of the best website-building tools out there.  Let's pick our differences from WP very carefully.

**Comment by danieltj27** [comment]
@nylen 

> Let's pick our differences from WP very carefully.

100% agree.

I think the list mentioned above would remove *_a lot_* of core functionality that is needed by various plugins. There will be a point of no return where ClassicPress isn't sustainable as a 'fork' anymore and becomes its own entity. Much like WordPress and b2/cafelog many moons ago.

The point in time will come and there will need to be a big decision made in how things continue. The infrastructure will be the biggest challenge I feel. WordPress.org does a huge amount behind the scenes that I feel must probably don't realise. It's a tightrope walk and we need to balance things very carefully.

**Comment by scottybo** [comment]
Just to chime in: This fork will be the LTS support version of ClassicPress for thoses who simply want to keep the WordPress experience minus Gutenberg and React.js

We will create a fork of this fork (codenamed: ClassicPress Plus) which will open up the voting for future developments.

**Comment by marctenax** [comment]
Absolutely agree Danieltj27; please: only one ClassicPress!

**Comment by senlin** [comment]
I also agree. There is enough confusion with WP/GB and ClassicPress is not going to make that any easier. To then add another version of that on top of that, will be too much I think.

**Comment by danieltj27** [comment]
I just worry that having two separate versions is going to make switching very difficult for people. Most 'less technical' people as you put it won't know what 'LTS' even is anyway so having two options makes things much, much more confusing.

I think the original idea of this project should remain unchanged with a fork of WordPress 4.9.8 and branch off that into a new system. Otherwise it feels like we're crossing wires and making unnecessary adjustments that will make it too difficult to sustain the project.

I'd like to contribute to ClassicPress but I fear there will be too much going on to contribute effectively and move the project forward as planned. We don't need to make it complicated. PHP versions and everything aside, it just needs to be a straight forward branch off the current latest version. Remove Gutenberg bits and then start iterating.

If there's going to be a 'vanilla' ClassicPress that just removes Gutenberg and that's it, then there's really no point and you might as well install the Classic Editor or stay at 4.9.8 forever. People won't want or even need to migrate over to ClassicPress if the only thing that changes is the code for the Gutenberg callout is removed.

**Comment by Mte90** [comment]
I want to see, will see.
Let's work on a project without gutenberg (that is already available).
Later we will see if there are stuff that we want for another version.

**Comment by marctenax** [comment]
Another step of reflection: everyone remembers that WordPress has planned v4.9.9 and also v4.9.10 before v5.0

**Comment by marctenax** [comment]
Also Privacy Tools is another thing to valuate.

**Comment by danieltj27** [comment]
> Gutenberg will start to make its mark over the next few minor releases.

The only thing of Gutenberg in core right now is the callout. They'll be nothing else until version 5.0 is released so arguably 4.9.10 - if that ever exists - will still be fine to fork.

**Comment by stefanos82** [comment]
As soon as @scottybo announced the project, the community reacted, which is something I have enjoyed; in my humble opinion, they needed it.

What bothers me though is this: what happens to ClassicPress if WordPress decides to stop pushing Gutenberg towards core and keeps it as a plugin instead?

What I wanted from WordPress for years now is:
- Better coding style that respects PSR-2
- Support for SQLite and PostgreSQL, especially SQLite to be the default database!
- Caching options by default, not in the form of a plugin, but as part of the actual core. Again, SQLite here could save the day.

If ClassicPress is going to go its own way, it should do so right from the very beginning and not at a later time.

Yes, I understand that we need to have a working version to offer to end-users that want to migrate from WordPress, but we definitely need to have a clear vision where the future of ClassicPress is or should be.

It really bothers me that WordPress core team does not respect its own community.

To be honest with you, I thought about forking it myself, but I didn't have the guts to do it.

I have had a few cases where clients wanted a website that could actually work with SQLite just fine and be as fast as a static website. The 5-minute installation would get reduced to 10-seconds installation, if not lower!

Does it make sense to you what I'm trying to say? :thinking:

**Comment by danieltj27** [comment]
> If ClassicPress is going to go its own way, it should do so right from the very beginning and not at a later time.

Absolutely. I don't think any changes to WordPress should make its way into ClassicPress. It should be a hard fork that goes in a new direction.

> Yes, I understand that we need to have a working version to offer to end-users that want to migrate from WordPress, but we definitely need to have a clear vision where the future of ClassicPress is or should be.

I personally believe the migration for end users is either not updating to 5.0/using Classic Editor plugin or switching ClassicPress which diverts into a different direction from WordPress. I don't think any support for WordPress should be made in ClassicPress because it'll be too hard to maintain compatibility for plugins and themes otherwise. It'll be easier to maintain the project if it goes off on a different roadmap.

**Comment by stefanos82** [comment]
@danieltj27 I agree with you.

I hope more people from WordPress community feel the same way and start helping with ClassicPress's stability to get closer to the very first release of it.

@scottybo I am a bit confused with the direction of the project to be honest with you.

The petition is a form of reaction towards the original project, which means, if the WP core team decides to listen to you, this project will ceased to exist.
In "Our Mission" part 5 though, you say "ClassicPress will be registered as a not-for-profit company (a Limited by Guarantee company based in the United Kingdom)".

Did you actually mean an independent non-profit Foundation here?

Also, what is the final direction of this project?

Can you please clarify the objective of ClassicPress? It's not clear to me.

**Comment by scottybo** [comment]
@stefanos82 Please see my comment in #22 - in essence there's a HUGE amount of work going on at the moment and the "what is ClassicPress" is something that is still evolving.

My vision is pretty simple, however. ClassicPress v1.0.0 is a fork of WordPress without Gutenberg which people will be able to switch to in the knowledge that it'll be compatible with their themes, plugins and will remain secure for the future.

This by itself requires a sh*t tonne of work. From API end points, to packaging zip files for all the various locales, to setting up hosting for these zips. The nuts and bolts of the project are my primary concern right now. 

My long term vision is that ClassicPress goes on its own development track and has features that are voted in by the community. I'm in the process of setting up a committee of around 20 people who will have the final say on features that are voted to be added (or removed from) ClassicPress so that we're sure that anything voted for by the community is 1) feasible and 2) in the best interest of those who use ClassicPress.

I need help - if someone is happy to step up and take on the website to ensure the messaging is correct, I'd gratefully accept!

**Comment by stefanos82** [comment]
Can you advised John O'Nolan, the Ghost.org creator about the wordpress.com style service? He's quite transparent about how they are making money with Ghost.

Also, a kind suggestion: since I don't use slack, are there any plans to register an IRC channel? I use it for decades now and I'm on Freenode on a daily basis.

**Comment by danieltj27** [comment]
> RE: The company - yes. ClassicPress Limited is now registered as a not-for-profit company. Running ClassicPress is going to cost money, potentially a lot of it. In order to fund it we're going to have to be able to take donations, potentially sell merchandise and maybe even provide a WordPress.com style service.

> To do this requires a legitimate business structure, annual tax returns, bank accounts and various other things. I've set this up as a not-for-profit so that it's clear I'm not in this for personal gain. Under UK law it's illegal for me to withdraw any profits. As I say, there's a lot going on behind the scenes!

I'd say that is very premature to setup ClassicPress without a clear roadmap of next steps right now. Currently ClassicPress isn't a 'thing' yet (no actual ClassicPress code).

There's no product or basis to work from just yet and I'm not comfortable being part of the project in its current state. I fear there may be legal issues around this 'semi fork' where code is taken from WordPress and put into this project effectively making it a mirror and what not. I have no legal background at all and could be way off base here, but I think there could be some kind of issue around doing something like that. I literally don't know.

I also feel like there's not much community discussion happening right now and having a non-profit running things doesn't really make this a community effort and more so just a select few running the show. I totally understand that's probably not the actual way forward it's intended to run, but it's just important to be mindful that it may appear that way.

I also don't think having a WordPress.com/Ghost.org model of selling managed hosting is the right steps either, at least not yet. It seems like the project is trying to run before it can walk. I'd be surprised if donations cover the costs of everything in these early stages. There needs to be a product on offer first and that'll require months of community led work to achieve.

**Comment by scottybo** [comment]
@danieltj27 there's a **huge** amount of discussion happening on Slack every day, I'd recommend joining in. There are **not** a select few running the show. The whole purpose of this fork is to bring the decision making back to the community. I can't recommend enough logging into Slack and reading through the discussions.

I appreciate the feedback about things being too soon for setting up a company, but the reality is that the world we live in is litigious and I need to protect myself. I have a house, a wife and a life to lead. **I'm not willing to put any of those on the line for a WordPress fork**.

**Comment by scottybo** [comment]
I'm closing this issue now for now.

The inaugural committe decided today (transcripts will be made available) that we will have a single fork. Version 1 will be a long term support version of ClassicPress based on the 4.9 branch. Following versions will introduce changes as voted for by the community.
