### ISSUE TITLE
This a proposal too add single_year_title() and single_day_title

### ISSUE THREAD

**Issue by benlumia007** [ClassicPress/ClassicPress#833]
I found that there's a function `single_month_title` but does not have `single_year_title` and `single_day_title`. To me it would make since to add some kind of functionaly similar so that we don't need to use `get_the_date()`

## Expected behavior

`single_month_title` displays October2021, `single_year_title` should display 2021 and `single_day_title` should display October 22, 2021

## Current behavior

`single_month_title` should need a space between the month and year by default and add `single_year_title` and `single_day_title`

## Possible solution

Is just a suggestion if we can add `single_year_title` and `single_day_title`

## Context

It just makes sense to add `single_year_title` and `single_day_title` if `single_month_title` exists.

**Comment by joyously** [comment]
You could also say that it would never be used, is one line, so why have it? Simply remove the unfiltered `single_month_title` function if you want parity.

**Comment by benlumia007** [comment]
that's what i was just gonna write.. why have `single_month_title` if is not gonna get use.. or no one knows about it.

**Comment by nylen** [comment]
Yes, I think `single_month_title` should be deprecated. It's not used anymore and it doesn't have localization. This is the only other reference to it in the code, which also does nothing because that filter is no longer called anywhere: https://github.com/ClassicPress/ClassicPress/blob/ef3693442b2b556a7693a64d0f3843982667e53d/src/wp-includes/default-filters.php#L110-L114

**Comment by benlumia007** [comment]
so i guess that we can deprecated which would definitely make more sense if no one uses it and is not localized whatsoever...
