### ISSUE TITLE
Make Grunt files compatible with Windows

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#854]
I'm not 100% sure, but I believe my issue with Grunt is due to Windows. Reading up on the error, I [found this](https://github.com/gotwarlost/istanbul#usage-on-windows):

> Istanbul assumes that the command passed to it is a JS file (e.g. Jasmine, vows etc.), this is however not true on Windows where npm wrap bin files in a .cmd file. Since Istanbul can not parse .cmd files you need to reference the bin file manually.

It's instructions from a different package on how to make it compatible with Windows, which was the [answer to the same error I have](https://github.com/gotwarlost/istanbul/issues/677).

## Expected behavior
`grunt precommit` works as expected.

## Current behavior
`grunt precommit` errors out:

```
PS C:\WinNMP\WWW\ClassicPress> grunt precommit
Running "rollup" task
Fatal error: C:\WinNMP\WWW\ClassicPress\node_modules\.bin\rollup:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

## Possible solution
Refer to description. It should help figuring out the issue.

**Comment by nylen** [comment]
The amount of work that this would require is frankly enormous. This error is coming from the `rollup` package (used to build the JavaScript files for the media library) which is not code that we control.

For now, Linux and OS X are supported, Windows is not. Maybe we should add a message/warning to that effect.

**Comment by nylen** [comment]
In the meantime you will need to use Windows Subsystem for Linux (or a full VM) for development.

**Comment by viktorix** [comment]
WSL is a good option. Took me a bit to get it set up since I had to re-install everything inside WSL.

Once everything was set up, I ran `npm install` and installed all the packages. Then I ran `grunt precommit`. It began processing stuff, but ended up with an error:

```
>> 110 errors in 27 files
Warning: Task "jshint:themes" failed. Use --force to continue.

Aborted due to warnings.
```

Is that normal? Should I try with --force?

**Comment by nylen** [comment]
This is most likely because you have other themes installed that are not part of core, and the `jshint:themes` task should not be checking these but it currently is:

https://github.com/ClassicPress/ClassicPress/blob/85b4f18bed60084b1a5e565d65389bf1c1cc516e/Gruntfile.js#L368-L379

Hopefully that is correct. We should fix it in core by making that line that says `twenty*/**/*.js` more specific to the themes we actually include.

In the meantime you can fix this by commenting out the line that says `jshint:themes` here:

https://github.com/ClassicPress/ClassicPress/blob/85b4f18bed60084b1a5e565d65389bf1c1cc516e/Gruntfile.js#L747-L754

This is better than using `--force` because `--force` will ignore all errors and continue, but you can just skip the `jshint:themes` check as long as you're not modifying the themes included with core (should be very infrequent).

Note also that you may want to run `grunt precommit:verify` instead. `precommit` may modify some files that you should then commit, but it won't tell you that anything was modified and you would need to check with `git status` afterwards. This probably needs to be documented better. Here is the related code:

https://github.com/ClassicPress/ClassicPress/blob/85b4f18bed60084b1a5e565d65389bf1c1cc516e/Gruntfile.js#L794-L801

**Comment by viktorix** [comment]
You're right, it was another theme. I most likely installed it to test stuff. I deleted it. Now, I got a new error 😁

```
Running "phpunit:wp-api-client-fixtures" (phpunit) task
Warning: Error: not found: phpunit Use --force to continue.

Aborted due to warnings.
```
Is this [Trac ticket](https://core.trac.wordpress.org/ticket/54008) related? 

Or do I need to install PHPUnit separately? Unless it was installed automatically by npm, I did not install PHPUnit.

**Comment by mattyrob** [comment]
@viktorix - That certainly looks like you need to install PHPUnit inside your WSL system. Make sue for the moment at least to get PHPUnit6 as the current code doesn't yet support higher versions.

**Comment by mattyrob** [comment]
I've been reading up on this as best I can (I don't have access to a Windows machine).

It seems a potential solution is the [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/about)

**Comment by KTS915** [comment]
Can we just add a note about that in some appropriate place? I don't think there's much else we can do here.
